// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  "app": {
    "applications": "应用",
    "cleanupQuick": "快速清理",
    "cleanupScan": "磁盘扫描",
    "comingSoon": "即将推出",
    "companion": {
      "hide": "隐藏 Robin",
      "show": "唤起 Robin"
    },
    "demoData": "浏览器演示数据",
    "diagnostics": "诊断",
    "history": "历史",
    "live": "实时",
    "mainNavigation": "主导航",
    "metrics": {
      "cpuContext": "{{count}} 个逻辑核心 · 单进程可超过 100%",
      "disk": "存储使用",
      "diskCapacityContext": "共 {{total}} · 可用 {{available}}",
      "diskContext": "读 {{read}} · 写 {{write}}",
      "memory": "内存使用",
      "memoryContext": "共 {{total}} · 交换 {{swap}}",
      "network": "网络吞吐",
      "networkContext": "下行 {{receive}} · 上行 {{send}}"
    },
    "metricsLabel": "系统资源摘要",
    "mode": {
      "label": "体验模式",
      "professional": "专业模式",
      "short": {
        "professional": "专业",
        "simple": "日常"
      },
      "simple": "日常模式",
      "switchTo": {
        "professional": "切换到专业模式",
        "simple": "切换到日常模式"
      }
    },
    "monitor": "监控",
    "network": "网络",
    "overview": "概览",
    "pause": "暂停",
    "paused": "已暂停",
    "processes": "进程",
    "refreshNow": "立即刷新",
    "resume": "继续",
    "sampleFailed": "采样暂时失败：{{message}}",
    "samplerConnecting": "正在连接本机采样器…",
    "samplerFailed": "无法启动采样器",
    "samplerNoData": "没有收到系统数据。",
    "settings": "设置",
    "soon": "稍后",
    "staleTarget": "目标进程身份已经变化，操作已取消。请重新选择并确认。",
    "startup": "启动项",
    "status": {
      "applicationCount": "{{count}} 个应用或系统组件",
      "cleanupEntries": "已检查 {{count}} 个项目",
      "interfacesAndConnections": "{{interfaces}} 个网络接口 · {{connections}} 个连接",
      "interval": "采样间隔 {{interval}} ms",
      "processCount": "{{count}} 个进程",
      "samplerSaved": "原生采样 {{time}} · 连续失败 {{failures}} 次",
      "samplerWaiting": "原生采样正在启动",
      "savedHistory": "{{count}} 个已保存历史点"
    },
    "storage": "存储",
    "switchLanguage": "切换界面语言",
    "tasks": {
      "activeCount": "{{count}} 个任务进行中",
      "cleanup": {
        "failed": "空间扫描未完成",
        "progress": "已检查 {{count}} 项",
        "title": "空间扫描"
      },
      "empty": "没有正在运行的任务",
      "emptyHint": "扫描、更新和盘点会统一显示在这里。",
      "files": {
        "failed": "文件核对未完成",
        "progress": "已检查 {{count}} 项",
        "title": "文件核对"
      },
      "folder": {
        "progress": "已检查 {{count}} 项",
        "title": "文件夹刷新"
      },
      "kicker": "后台任务",
      "needsAttention": "任务需要处理",
      "open": "返回任务",
      "preparing": "正在准备…",
      "retry": "查看并重试",
      "startup": {
        "failed": "启动项盘点未完成",
        "title": "启动项盘点"
      },
      "title": "任务中心",
      "update": {
        "current": "CoreRobin 更新",
        "installError": "更新安装未完成",
        "installing": "正在下载并安装更新",
        "ready": "更新已就绪",
        "restartError": "需要重新启动应用"
      }
    },
    "technicalOverview": {
      "description": "展开 CPU、内存、磁盘、网络和五分钟趋势。",
      "title": "查看实时资源详情"
    },
    "viewEyebrow": {
      "applications": "应用影响",
      "cleanup": "空间清理",
      "history": "历史分析",
      "network": "网络诊断",
      "overview": "系统概览",
      "processes": "进程诊断",
      "settings": "偏好设置",
      "startup": "启动项检查",
      "storage": "存储诊断"
    }
  },
  "applications": {
    "center": {
      "boundary": "只按稳定应用身份关联本机数据，不保存命令行或文件内容。",
      "connectionCount": "当前 {{count}} 个连接",
      "description": "在同一个应用身份下查看当前占用、启动行为、网络活动、历史记录与卸载入口。",
      "history": "历史记录",
      "historySamples": "已保存 {{count}} 个样本",
      "kicker": "统一应用视图",
      "localIdentity": "本机应用身份",
      "manage": "管理应用",
      "manageHint": "检查残留文件或卸载",
      "network": "网络活动",
      "selected": "当前应用",
      "startup": "启动行为",
      "startupCount": "关联 {{count}} 个启动项",
      "tabs": {
        "activity": "当前活动",
        "history": "历史归因",
        "label": "应用中心页面",
        "manage": "管理与卸载"
      },
      "title": "应用中心"
    },
    "description": "CoreRobin 会把辅助进程合并到熟悉的应用名称下，再汇总 CPU、内存和磁盘活动。",
    "disk": "磁盘",
    "empty": "没有匹配的应用",
    "energy": {
      "activity": "GPU 活动 {{value}}",
      "applicationImpact": "活跃进程相对能耗",
      "boundary": "这些数值只是操作系统提供的相对分数，不是瓦特或电量；零值不进入排行，展开时每 15 秒低频刷新。",
      "collapsedDescription": "按需排查图形负载；默认不持续采样，也不参与健康判断。",
      "cores": "{{count}} 核",
      "description": "系统支持时显示 GPU 活动和活跃进程的相对能耗线索。",
      "eyebrow": "可选扩展指标",
      "gpu": "GPU",
      "gpuUnavailable": "当前平台或硬件未提供可用的 GPU 指标。",
      "noProcessActivity": "本次采样没有检测到可区分的进程能耗活动。",
      "onDemand": "按需采样",
      "processUnavailable": "当前平台未提供按进程的能耗影响。",
      "title": "GPU 与相对能耗"
    },
    "kicker": "应用级汇总",
    "level": {
      "critical": "影响明显",
      "high": "影响较高",
      "low": "影响较低",
      "moderate": "有些影响"
    },
    "memory": "内存",
    "nativeUninstall": {
      "boundary": "这个应用由操作系统安装目录管理；CoreRobin 只会把已验证的短期包身份交给原生卸载器。",
      "confirm": "开始系统卸载",
      "dialogBoundary": "前端不会提交卸载器路径或命令行。",
      "dialogDescription": "CoreRobin 将启动已验证的包管理器方式；任何授权弹窗都由操作系统提供。",
      "dialogTitle": "使用操作系统卸载 {{name}}",
      "elevationLabel": "授权",
      "elevationNotRequired": "预计无需管理员批准",
      "elevationPrompt": "可能出现 Windows UAC 或 Linux PolicyKit 授权；取消授权会与执行失败分别展示。",
      "elevationRequired": "操作系统可能会请求管理员批准",
      "methodLabel": "系统方式",
      "outcome": {
        "cancelled": "已取消 {{name}} 的系统卸载。",
        "failed": "系统卸载器未能移除 {{name}}。",
        "restart_required": "{{name}} 已移除；操作系统要求重新启动。",
        "succeeded": "操作系统已卸载 {{name}}。"
      },
      "relatedData": "不会猜测或自动删除关联数据；由包管理器判断哪些已安装文件属于这个应用。",
      "revalidate": "执行前会立即重新核对包身份。",
      "review": "复核 {{name}} 的系统卸载",
      "source": {
        "linux_deb": "Debian 软件包",
        "linux_flatpak": "Flatpak",
        "linux_rpm": "RPM 软件包",
        "linux_snap": "Snap",
        "macos_bundle": "macOS 应用包",
        "portable": "便携或手动安装",
        "unknown": "未知来源",
        "windows_msi": "Windows Installer（MSI）",
        "windows_msix": "Windows 应用包（MSIX）",
        "windows_uninstaller": "Windows 注册卸载器"
      },
      "sourceLabel": "安装来源",
      "submitting": "正在等待系统卸载器…",
      "systemManaged": "系统托管卸载",
      "unavailable": {
        "portable": "没有找到可信的包管理器身份；该项目保持只读。",
        "protected": "不能从这里卸载 CoreRobin 自身或受保护的系统组件。"
      }
    },
    "overviewTitle": "现在谁影响最大",
    "processCount": "{{count}} 个相关进程",
    "safety": "点击应用只会打开资源证据；任何结束操作仍需单独确认。",
    "search": "搜索应用",
    "searchPlaceholder": "按应用名称搜索",
    "selected": {
      "appSafety": "这是普通应用。CoreRobin 不会自动关闭它，结束操作仍需单独确认。",
      "balanced": "当前没有某一项资源特别突出，整体影响较低。",
      "cpu": "当前主要影响来自处理器占用（{{value}}）。持续偏高时可能导致卡顿、发热或耗电增加。",
      "disk": "当前主要影响来自磁盘活动（{{value}}）。同步、下载或构建任务都可能造成短时读写。",
      "memory": "当前主要影响来自内存占用（{{value}}）。只有同时出现内存压力和交换活动时才需要处理。",
      "professionalDetails": "用专业模式查看进程",
      "systemSafety": "这是系统组件，不建议直接结束；如有异常请先查看专业证据。",
      "title": "{{name}} 的影响说明"
    },
    "sort": {
      "cpu": "CPU",
      "disk": "磁盘",
      "impact": "综合影响",
      "memory": "内存"
    },
    "sortLabel": "应用排序方式",
    "systemComponent": "系统组件 · 不建议结束",
    "title": "应用资源影响",
    "trashWatcher": {
      "description": "可选的本机 30 秒检查；只提供能够明确确认归属的残留计划，绝不自动删除。",
      "empty": "当前用户的废纸篓中没有待检查的应用。",
      "error": "暂时无法检查废纸篓。",
      "found": "已移入废纸篓 · 检查残留",
      "planBoundary": "应用本体已经在废纸篓中；此计划只包含仍然存在且能够明确确认归属的支持数据。",
      "title": "观察移入废纸篓的应用"
    },
    "uninstall": {
      "appIdentifier": "应用标识",
      "applicationUnit": "个应用",
      "artifacts": {
        "application": "应用本体",
        "application_support": "应用支持数据",
        "cache": "缓存",
        "container": "沙盒容器",
        "cookies": "Cookie 数据",
        "http_storage": "网络存储",
        "launch_agent": "用户启动代理",
        "logs": "日志",
        "preferences": "偏好设置",
        "saved_state": "窗口恢复状态",
        "web_data": "网页数据"
      },
      "bundleOnlyBoundary": "此应用没有提供足够的身份信息，因此只卸载经过路径与结构验证的应用本体，不猜测或删除残留文件。",
      "cachedInventory": "显示 {{time}} 的本机缓存，可随时刷新",
      "cannotPrepare": "无法为这个应用生成安全计划",
      "description": "识别应用本体和能够明确确认归属的残留文件；每个路径都由你确认后才会处理。",
      "dialogDescription": "请逐项核对应用本体和相关数据。默认移入废纸篓，仍可恢复。",
      "dialogTitle": "卸载 {{name}}",
      "empty": "没有匹配的应用",
      "errors": {
        "application_artifact_unavailable": "某个项目在确认前发生变化，请刷新卸载计划。",
        "application_bundle_identifier_missing": "无法确认此应用的身份。",
        "application_bundle_unavailable": "应用当前不可访问，请确认它仍在原位置。",
        "application_identity_changed": "应用身份已经变化，请刷新清单后重试。"
      },
      "filters": {
        "all": "全部",
        "days": "{{count}} 天未使用",
        "sort": "排序",
        "sortBy": {
          "last_used": "最久未使用",
          "name": "按名称",
          "size": "按大小降序",
          "source": "按安装来源"
        },
        "source": "安装来源",
        "unused": "最近使用"
      },
      "foundItems": "已确认归属的项目",
      "installedSize": "应用本体",
      "kicker": "应用管理",
      "localOnly": "仅在本机读取，不上传清单",
      "outcomeComplete": "{{name}} 已处理 {{count}} 项，共 {{size}}。",
      "outcomeDeletedPermanently": "{{name}} 已直接删除；共处理 {{count}} 项、{{size}}。",
      "outcomeMovedToTrash": "{{name}} 已移至废纸篓；共处理 {{count}} 项、{{size}}，清空废纸篓前仍可恢复。",
      "outcomePartial": "{{name}} 的卸载未完全结束；已处理 {{count}} 项，共 {{size}}。",
      "planBoundary": "请先退出这个应用。这里只列出能够明确确认属于它的路径，不按名称猜测。",
      "planKicker": "卸载计划",
      "preparingPlan": "正在核对应用身份和残留文件…",
      "refresh": "刷新应用",
      "removed": {
        "partial": "应用本体已经移除，但部分相关项目未能处理。",
        "permanent": "已直接删除",
        "permanentDescription": "应用已经从磁盘直接删除，无法从废纸篓恢复；主动刷新清单后将移除这条记录。",
        "trash": "已移至废纸篓",
        "trashDescription": "应用已经离开原位置，可在清空废纸篓前恢复；主动刷新清单后将移除这条记录。"
      },
      "required": "必选",
      "reveal": "在访达中显示应用",
      "review": "检查并卸载 {{name}}",
      "scanKicker": "本机应用索引",
      "scanning": "正在读取应用清单…",
      "scanningHint": "正在核对应用、占用空间和身份信息；大型应用可能需要多一点时间。",
      "search": "搜索已安装应用",
      "searchPlaceholder": "搜索名称、应用标识或路径",
      "selectDescription": "助手会先生成逐路径卸载计划，再进入最终确认。",
      "selectTitle": "选择一个应用",
      "selectedSize": "已选 {{count}} 项",
      "skipped": "{{count}} 个项目未纳入计划",
      "skippedDescription": "这些路径的当前状态无法安全确认，助手不会处理它们。",
      "title": "彻底卸载助手",
      "unavailable": {
        "application_bundle_identifier_missing": "应用没有提供足够的身份信息。",
        "application_bundle_invalid": "应用包结构不完整或不受支持。",
        "application_bundle_not_allowed": "只支持“应用程序”目录中的顶层应用。",
        "current_application_protected": "CoreRobin 运行期间不能卸载自身。",
        "generic": "此应用无法通过当前安全规则卸载。"
      },
      "unsupportedDescription": "未能读取受支持的 macOS、Windows 或 Linux 应用清单。请等待系统完成应用或软件包数据库更新后重试。",
      "unsupportedTitle": "系统应用清单暂不可用"
    },
    "viewAll": "查看全部应用"
  },
  "cleanup": {
    "access": {
      "bundleMissingDescription": "macOS 无法把开发进程加入权限列表。请先安装 CoreRobin.app 并从“应用程序”中重新打开；目前仍可执行有限扫描。",
      "bundleMissingTitle": "当前运行的不是可授权的应用包",
      "bundleRequired": "需先从 CoreRobin.app 启动",
      "checkAgain": "我已授权，重新检查",
      "checking": "正在检查权限…",
      "checkingReturn": "正在确认授权状态…",
      "continueLimited": "扫描可访问区域",
      "description": "macOS 会保护邮件、信息和其他应用数据等位置。授予“完全磁盘访问权限”后，空间地图才能尽量完整；CoreRobin 仍然只读取文件名、大小和时间等元数据。",
      "kicker": "扫描前准备",
      "openAgain": "重新打开系统设置",
      "openSettings": "打开完全磁盘访问权限",
      "privacy": "权限由 macOS 管理，可随时在系统设置中关闭。CoreRobin 不读取文件内容，也不会在扫描时修改任何文件。",
      "revealApp": "在访达中显示应用",
      "steps": {
        "add": "点击 +，选择 CoreRobin.app",
        "open": "打开系统设置",
        "return": "开启开关并返回"
      },
      "title": "允许查看整个系统磁盘",
      "unknown": "暂时无法确认权限状态；你仍可以打开系统设置授权，或执行有限扫描。",
      "waiting": "系统设置已打开。如果列表中没有 CoreRobin，请点击列表下方的 +，选择 CoreRobin.app；开启后返回，扫描会自动开始。"
    },
    "cancelScan": "停止扫描",
    "cancelling": "正在停止…",
    "categories": {
      "title": "这些空间大多用来做什么"
    },
    "coverage": {
      "continueComplete": "继续完整扫描",
      "quickLimit": "其他磁盘区域尚未扫描；此结果不会冒充完整磁盘统计。",
      "quickResult": "已精确检查 {{count}} 个常用位置，找到 {{size}} 内容",
      "title": "扫描范围"
    },
    "deleteDialog": {
      "cancelDelete": "停止删除",
      "cancelHint": "已完成的项目不会自动还原；CoreRobin 会在当前文件操作结束后停止。",
      "cancelling": "正在停止…",
      "changed": "扫描后有变化",
      "changedWarning": "其中 {{count}} 项内容发生了变化，大小和文件数已更新。请重新检查后继续。",
      "confirm": "永久删除 {{count}} 项",
      "confirmTrash": "移到废纸篓（{{count}} 项）",
      "deleteConfirmDescription": "文件不会进入废纸篓，下载文件、配置与个人数据可能无法重新生成。",
      "deleteConfirmTitle": "我明白这些内容会被永久删除",
      "deleting": "正在永久删除…",
      "description": "选择移到废纸篓，或确认后直接从磁盘永久删除。",
      "errors": {
        "cleanup_confirmation_unavailable": "本次确认已经失效，请取消后重新打开检查窗口。",
        "cleanup_cross_filesystem": "所选目录进入了另一个磁盘或挂载点，CoreRobin 已拒绝递归删除。",
        "cleanup_target_changed": "文件在确认后又发生了变化，因此没有删除任何内容。请取消后重新检查。",
        "cleanup_target_conflicts_with_trash": "所选内容包含废纸篓或已经在废纸篓中，只能选择直接删除。",
        "cleanup_target_outside_home": "出于安全考虑，CoreRobin 只处理个人目录或获准临时位置内的内容。",
        "cleanup_target_unavailable": "部分内容已经不存在或暂时无法访问，请重新扫描后再试。",
        "cleanup_trash_unavailable": "CoreRobin 当前无法安全使用系统废纸篓。所选内容尚未处理，请稍后重试。",
        "invalid_cleanup_selection": "清理篮中的选择无效，请重新选择后再试。",
        "overlapping_cleanup_targets": "同时选择了文件夹和它的子内容，请只保留其中一层。",
        "protected_cleanup_path": "CoreRobin 不会删除操作系统位置、凭据与密钥、受保护的数据资料库根、临时目录根、主目录或废纸篓目录本身。"
      },
      "estimatedSize": "预估大小",
      "irreversible": "无法撤销",
      "itemUnit": "项内容",
      "modeTitle": "处理方式",
      "permanentModeDescription": "立即释放空间，不经过废纸篓。",
      "permanentModeTitle": "直接删除",
      "preparing": "正在准备清理…",
      "progressCancelling": "正在安全停止",
      "progressCurrent": "当前：{{name}}",
      "progressDeleted": "已释放约 {{size}}",
      "progressDeleting": "正在永久删除",
      "progressEntries": "{{processed}} / {{total}} 个文件与文件夹",
      "progressInspecting": "正在处理文件与文件夹",
      "progressMoved": "已移动约 {{size}}",
      "progressMovingToTrash": "正在移到废纸篓",
      "progressPreparing": "正在准备删除",
      "progressTargets": "已完成 {{completed}} / {{total}} 项",
      "recheckSelection": "重新检查并继续",
      "recommended": "推荐",
      "recoverable": "可从废纸篓恢复",
      "selection": "所选内容",
      "title": "检查清理篮中的内容",
      "trashConfirmDescription": "原路径将立即释放；清空废纸篓前仍可恢复。",
      "trashConfirmTitle": "我确认把这些内容移到废纸篓",
      "trashModeDescription": "保留恢复机会，可稍后在废纸篓中找回。",
      "trashModeTitle": "移到废纸篓"
    },
    "description": "完整扫描系统磁盘，按真实文件路径查看空间占用。",
    "entriesScanned": "已检查 {{count}} 个项目",
    "estimateBoundary": "这是缓存与废纸篓的估算值，不代表必须清理。",
    "failed": "无法完成空间扫描",
    "fileInsights": {
      "back": "返回空间清理",
      "boundary": "这里只提供证据和路径操作，不会自动删除。长期未用按修改时间判断，不等同于最后访问时间。",
      "cancel": "停止检查",
      "completeDescription": "先从可回收空间最大的重复组开始核对。",
      "completeKicker": "检查完成",
      "completeTitle": "文件线索已经整理好",
      "copies": "{{count}} 个副本",
      "copyIndex": "第 {{count}} 份",
      "description": "独立检查常用个人目录，先用大小筛选候选，再在本机核对内容指纹。",
      "duplicateGroups": "重复文件组",
      "duplicates": "内容完全相同",
      "duration": "检查用时",
      "empty": "仅在你点击检查后读取候选文件内容并计算本机 SHA-256，不会上传。",
      "emptyResultTitle": "这一类结果很干净",
      "eyebrow": "主动只读检查",
      "groupLabel": "相同内容组",
      "groupSavings": "保留一份后可回收",
      "launcherDescription": "进入独立工作区，查看扫描过程、重复内容组和长期未修改大文件。",
      "loadingKicker": "本机内容雷达",
      "loadingPrivacy": "哈希只在本机计算，不上传文件名、路径或内容。",
      "localOnly": "完全在本机完成",
      "longUnmodified": "180 天未修改且超过 100 MB",
      "metrics": {
        "candidates": "候选文件",
        "hashed": "已核对内容",
        "scanned": "已查看项目"
      },
      "noDuplicates": "已检查的候选中没有发现重复内容。",
      "noOldFiles": "没有发现符合条件的大文件。",
      "oldFileLabel": "长期未修改文件",
      "oldFiles": "长期未修改",
      "openWorkspace": "打开工作区",
      "phase": {
        "discovering": "正在发现候选文件",
        "hashing": "正在核对重复内容"
      },
      "phaseDescription": {
        "discovering": "正在遍历常用个人目录，仅读取名称、大小和修改时间，快速缩小需要核对内容的范围。",
        "hashing": "正在读取大小相同的候选文件并计算本机 SHA-256，内容不会离开这台电脑。"
      },
      "phaseLabel": "检查阶段",
      "possibleSavings": "可能可回收",
      "processing": {
        "actionName": "重复文件处理",
        "cancelled": "处理已停止，已完成 {{count}} 个",
        "completed": "已处理 {{count}} 个重复副本，释放 {{size}}",
        "dialogDescription": "每个重复组至少保留一份；可移动到废纸篓，或确认后直接删除。执行前会再次核对文件状态和受保护路径。",
        "dialogTitle": "处理重复文件",
        "emptySelection": "选择需要处理的重复组，并确认每组要保留的文件。",
        "keep": "保留这份",
        "keepFile": "将 {{name}} 设为保留项",
        "kept": "保留",
        "partial": "已处理 {{deletedCount}} 个，{{failedCount}} 个未能处理",
        "planned": "待处理",
        "refreshIncomplete": "CoreRobin 无法按路径匹配全部重新核对后的重复文件。",
        "review": "检查处理方式",
        "selectGroup": "处理本组副本",
        "selectedGroup": "已选择本组",
        "selectionHint": "每个选中的重复组都会明确保留一份，只处理其余副本。",
        "summary": "已选择 {{count}} 个多余副本，共 {{size}}"
      },
      "progress": "已查看 {{scanned}} 项 · 候选 {{candidates}} 个 · 已哈希 {{hashed}} 个",
      "resultNavigation": "结果分类",
      "running": "正在核对",
      "scan": "检查文件",
      "scanAgain": "重新检查",
      "scope": {
        "desktop": "桌面",
        "documents": "文稿",
        "downloads": "下载",
        "movies": "影片",
        "music": "音乐",
        "pictures": "图片"
      },
      "scopeTitle": "检查范围",
      "steps": {
        "filterDescription": "先比较大小与元数据",
        "filterTitle": "快速筛选",
        "hashDescription": "本机计算 SHA-256",
        "hashTitle": "内容指纹",
        "reviewDescription": "保留路径和时间证据",
        "reviewTitle": "逐组核对"
      },
      "title": "重复与长期未修改文件",
      "truncated": "为控制扫描成本，本次结果达到安全上限，仅展示已完成部分。",
      "welcomeDescription": "CoreRobin 会先快速筛选大小相同的文件，再逐个核对内容指纹，同时单独整理长期未修改的大文件，结果只供你判断。",
      "welcomeTitle": "让相同内容浮出水面，而不是只比较文件名",
      "workspaceKicker": "文件核对工作区"
    },
    "fullDiskAccessHint": "macOS 上可在“系统设置 → 隐私与安全性 → 完全磁盘访问权限”中授权 CoreRobin 后重新扫描。",
    "growth": {
      "noGrowth": "紧凑快照中没有发现持续增长的目录。",
      "since": "与 {{time}} 的结果对比",
      "title": "较上次扫描的空间变化"
    },
    "itemCount": "{{count}} 个文件",
    "kicker": "深度分析",
    "largeFileBoundary": "只列出超过 500 MB 的文件，不建议自动删除",
    "largestFiles": "系统磁盘中的大文件",
    "locations": {
      "app_cache": {
        "description": "应用可能在之后重新生成或下载。",
        "title": "应用缓存"
      },
      "developer_cache": {
        "description": "构建工具与包管理器可重新生成的内容。",
        "title": "开发缓存"
      },
      "downloads": {
        "description": "可能包含安装包、文档和仍需保留的内容。",
        "title": "下载文件"
      },
      "hidden_data": {
        "description": "点号开头的应用数据和配置；核对具体内容后可以加入清理篮。",
        "title": "用户隐藏目录"
      },
      "trash": {
        "description": "清空后通常无法从废纸篓恢复。",
        "title": "废纸篓"
      }
    },
    "map": {
      "addToBasket": "加入清理篮",
      "allScanned": "全部扫描结果",
      "allocatedSize": "实际占用",
      "ariaLabel": "{{name}} 的空间扇形图",
      "back": "返回上一级",
      "basket": {
        "cancelled": "清理已停止，已完成 {{deletedCount}} 项",
        "clear": "清空",
        "collected": "已在清理篮",
        "collectedHint": "已经收集；可在下方清理篮中移除或继续核对",
        "completed": "已处理 {{deletedCount}} 项",
        "empty": "拖动扇区或右侧目录到这里，先收集再处理",
        "partial": "已处理 {{deletedCount}} 项，{{failedCount}} 项未能处理",
        "protectedBadge": "受保护",
        "protectedMessage": "系统文件与重要配置受到保护，未加入清理篮",
        "protectedPreview": "受保护，不能删除",
        "protectedTitle": "受保护目标",
        "release": "松手加入清理篮",
        "remove": "从清理篮移除 {{name}}",
        "title": "清理篮"
      },
      "breadcrumbs": "空间图层级",
      "categoryRoot": "用途分类",
      "centerBack": "返回上一级目录",
      "chooseDeleteMethod": "选择删除方式",
      "deleteResult": {
        "cancelled": "已停止清理，完成了 {{deletedCount}} 项",
        "cancelledNoDeletion": "已停止清理，没有内容被完整处理",
        "failed": "没有处理任何内容，{{failedCount}} 项失败",
        "partial": "已处理 {{deletedCount}} 项，另有 {{failedCount}} 项失败",
        "pendingReclaim": "已处理 {{processed}}，目前可用空间增加 {{size}}；差额可能仍由 APFS 快照、可清理空间或系统回收延迟占用",
        "reclaimed": "本次已处理约 {{size}} 的物理占用",
        "released": "文件系统可用空间已增加约 {{size}}",
        "selectedSizes": "所选逻辑大小 {{logical}}，物理占用 {{allocated}}",
        "success": "已完成 {{deletedCount}} 项清理",
        "trashSpace": "内容已移到废纸篓；清空废纸篓前通常不会释放对应空间"
      },
      "deletionUnavailable": "清理暂不可用",
      "description": "扇形面积按磁盘实际占用计算；同色系表示同一目录分支，灰色表示文件。",
      "descriptionCategory": "按常见用途重新汇总同一次扫描结果；分类是理解空间的辅助视角，不代表真实目录层级。",
      "descriptionPath": "按系统磁盘的真实文件路径展示：每一圈对应下一层目录，色块面积表示磁盘实际占用。",
      "details": "空间明细",
      "directActionHint": "拖动扇区或右侧目录到底部清理篮",
      "freshness": {
        "cached": "正在显示上次扫描结果",
        "changed": "此目录内容已变化，大小可能不准确",
        "changedShort": "内容已变化",
        "expired": "扫描结果较旧，建议重新扫描",
        "refreshFolder": "刷新 {{name}}",
        "refreshingFolder": "正在刷新 {{name}}…",
        "updating": "正在更新扫描，上一次空间地图仍可使用"
      },
      "grouped": "汇总分类",
      "includedByParent": "已随上级文件夹加入",
      "loadDeeperHint": "选择这个目录即可从本机索引打开下一层。",
      "loadFailed": "无法读取目录索引",
      "loadMore": "再显示 50 项",
      "loadingFolder": "正在读取目录索引…",
      "logicalSize": "文件标称 {{size}}",
      "mode": {
        "category": "用途分类",
        "label": "空间图展示方式",
        "path": "文件路径"
      },
      "noDeeperBreakdown": "当前层级没有更细的目录分组。",
      "otherContent": "其余内容",
      "otherContentHint": "这里仅汇总当前页未显示或未单独保存的文件；所有子文件夹都已收录，可用“再显示 50 项”继续浏览目录。",
      "planSummary": "已选择 {{count}} 项，共 {{size}}",
      "protectedSelectionHint": "系统目录和个人目录根节点仅供查看；个人目录内的具体内容可以加入清理篮",
      "refreshFailed": "无法刷新文件夹",
      "refreshProgress": "已检查 {{count}} 项 · {{time}} 秒",
      "removeFromBasket": "移出清理篮",
      "restrictedHint": "系统未授予读取权限，此项不会加入清理篮",
      "restrictedObjects": "无法读取的对象",
      "selected": "当前选择",
      "selectedPath": "当前选择路径",
      "title": "空间都去了哪里",
      "trashRootProtected": "废纸篓目录本身不会被删除；进入里面选择需要清理的具体内容",
      "types": {
        "aggregate": "合并的小对象",
        "file": "文件",
        "folder": "文件夹",
        "restricted": "受限内容"
      },
      "unreadable": "无法读取",
      "view": {
        "ascending": "从小到大",
        "clearSearch": "清空搜索",
        "descending": "从大到小",
        "empty": "当前文件夹没有匹配内容",
        "label": "浏览方式",
        "list": "列表",
        "loadFailed": "列表读取失败，请重试",
        "loading": "正在读取索引…",
        "map": "空间图",
        "search": "搜索当前文件夹",
        "sortName": "按名称",
        "sortSize": "按占用大小"
      }
    },
    "morePaths": " 等 {{count}} 个位置",
    "noLargeFiles": "可访问的系统磁盘位置中没有发现超过 500 MB 的文件。",
    "oldFileProcessing": {
      "actionName": "长期未修改文件清理",
      "cancelled": "处理已停止，已完成 {{count}} 个",
      "completed": "已处理 {{count}} 个长期未修改文件，释放 {{size}}",
      "dialogDescription": "复核选中的文件后，可将其移到废纸篓，或确认后直接删除；已不存在的文件会自动跳过。",
      "dialogTitle": "处理长期未修改文件",
      "emptySelection": "请选择已经确认不再需要的长期未修改文件。",
      "partial": "已处理 {{deletedCount}} 个，{{failedCount}} 个未能处理",
      "refreshIncomplete": "CoreRobin 无法按路径匹配全部重新核对后的长期未修改文件。",
      "review": "检查清理方式",
      "select": "选择",
      "selectFile": "选择 {{name}} 进入清理复核",
      "selected": "已选择",
      "selectionHint": "只有你明确选择的文件才会加入清理篮复核。",
      "summary": "已选择 {{count}} 个长期未修改文件，共 {{size}}"
    },
    "pathUnavailable": "没有可扫描路径",
    "profiles": {
      "complete": {
        "description": "顺序遍历整个系统磁盘，耗时更长",
        "title": "完整扫描"
      },
      "label": "扫描模式",
      "quick": {
        "description": "精确检查常见的大空间与可清理位置",
        "scope": "下载、桌面、文稿、媒体文件夹、废纸篓，以及常见应用和开发缓存。应用支持数据、容器和其他隐藏目录可用完整扫描查看。",
        "scopeTitle": "本次会检查",
        "title": "快速扫描"
      },
      "recommended": "推荐"
    },
    "progress": {
      "discovered": "已发现",
      "elapsed": "已用时",
      "entries": "已检查",
      "finalizing": "正在整理空间地图",
      "finalizingDescription": "文件夹已经扫描完成。CoreRobin 正在汇总索引并替换上次结果，磁盘内容较多时可能还需要一点时间。",
      "foundSpace": "已找到的内容",
      "locations": {
        "appCache": "应用缓存",
        "applications": "已安装应用",
        "developerCache": "开发工具缓存",
        "downloads": "下载文件",
        "hiddenData": "隐藏的应用数据",
        "personal": "个人文件",
        "systemDisk": "系统磁盘",
        "trash": "废纸篓"
      },
      "paused": "电脑已休眠，唤醒后将继续扫描",
      "recoveryFailed": "CoreRobin 无法继续跳过一个或多个异常文件夹。你可以停止扫描后改为扫描较小的范围。",
      "scanningLocation": "正在分析{{location}}",
      "stageKicker": "空间地图生成中",
      "stalled": "正在自动恢复扫描",
      "stalledDescription": "CoreRobin 会跳过当前无法读取的位置，并从已保存的进度继续扫描，无需重新开始。",
      "stalledTitle": "正在跳过无响应的文件夹"
    },
    "quickClean": {
      "again": "再清理一次",
      "analyze": "开始分析",
      "analyzeAgain": "重新分析",
      "analyzing": "正在分析…",
      "analyzingHint": "正在统计缓存、日志、临时文件与废纸篓…",
      "back": "返回空间扫描",
      "cancel": "取消",
      "category": {
        "logs": "日志文件",
        "temp_files": "临时文件",
        "trash": "废纸篓",
        "user_cache": "应用缓存"
      },
      "clean": "清理 {{size}}",
      "cleaning": "正在清理…",
      "close": "完成",
      "description": "一键清理缓存、日志、临时文件和废纸篓，不触碰你的文档与照片。",
      "done": "清理完成",
      "empty": "没有可清理的内容，磁盘很干净！",
      "freedSoFar": "已释放 {{size}}",
      "freedSummary": "释放了 {{size}}，共 {{count}} 个项目",
      "guideAction": "去磁盘扫描",
      "guideDescription": "深度扫描整个磁盘，按真实文件路径查看空间占用，再决定清理什么。",
      "guideTitle": "想清理得更彻底？",
      "kicker": "无需扫描",
      "launcherDescription": "不扫描，一键清理缓存、日志、临时文件与废纸篓。",
      "noRiskNote": "只清理可再生的缓存与已丢弃的废纸篓内容，不含你的文档、照片和登录信息。",
      "open": "打开快速清理",
      "skippedNote": "{{count}} 个项目正在被占用，已安全跳过。",
      "title": "快速清理",
      "total": "共可释放",
      "unavailable": "不可用"
    },
    "readOnlyDescription": "扫描会在后台读取文件名、大小等元数据直至完成，不读取文件内容，也不会修改、移动或上传文件。",
    "readOnlyTitle": "先看清楚，再决定是否处理",
    "reclaimableEstimate": "可能可回收空间",
    "restartScan": "重新开始扫描",
    "results": {
      "moreDescription": "按用途查看常见位置，或逐项检查大文件。",
      "moreTitle": "更多扫描结果"
    },
    "reviewFirst": "逐项确认",
    "safety": {
      "reclaimable": "通常可回收",
      "review": "必须确认"
    },
    "safetyBoundary": "扫描没有时间或数量上限，也不会跟随符号链接；只有放入清理篮、核对路径并明确确认的内容才会移到废纸篓或永久删除。",
    "scanAgain": "重新扫描",
    "scanDuration": "用时 {{seconds}} 秒",
    "scanErrors": {
      "targetUnavailable": "所选位置当前无法读取。请确认它仍然存在且可访问，然后重试。"
    },
    "scanning": "扫描中…",
    "snapshot": {
      "cached": {
        "description": "无需重新等待即可继续查看；切换目录只读取本机索引，不会访问文件系统。",
        "title": "已恢复上次扫描结果"
      },
      "expired": {
        "description": "CoreRobin 仍保留空间图，方便你继续查看；涉及清理前建议先更新一次结果。",
        "title": "这份结果已超过 24 小时"
      },
      "refresh": "更新结果",
      "retained": "结果已索引在本机；浏览目录不会重新扫描"
    },
    "startScan": "开始只读扫描",
    "targets": {
      "chooseFolder": "选择文件夹",
      "chooseFolderTitle": "选择一个要扫描的文件夹",
      "kicker": "扫描范围",
      "readOnlyNotice": "外置卷和文件夹仅做只读扫描；文件处理仍复用现有的清理篮确认流程。",
      "recent": "最近扫描",
      "removable": "可移除",
      "systemDisk": "系统磁盘",
      "title": "选择要扫描的位置"
    },
    "title": "磁盘扫描",
    "unavailable": "当前平台不可用",
    "unreadable": "有 {{count}} 个位置受权限保护或暂时无法读取，只有这些位置未计入结果。"
  },
  "common": {
    "average": "平均",
    "cancel": "取消",
    "close": "关闭",
    "current": "当前",
    "disabled": "未启用",
    "earlier": "较早",
    "enabled": "已启用",
    "errors": "{{count}} 个错误",
    "fiveMinutes": "最近 5 分钟",
    "fiveMinutesBack": "−5 分钟",
    "loading": "正在加载…",
    "none": "无",
    "now": "现在",
    "pathActions": {
      "copied": "已复制绝对路径",
      "copy": "复制路径",
      "errors": {
        "homeUnavailable": "CoreRobin 无法定位你的用户目录。",
        "openFailed": "系统暂时无法打开这项内容。",
        "unavailable": "这项内容已经不存在或暂时无法访问。",
        "unresolved": "CoreRobin 无法解析这个文件路径。"
      },
      "preview": "快速预览",
      "reveal": "在 Finder 中显示"
    },
    "peak": "峰值",
    "read": "读取",
    "refresh": "刷新",
    "retry": "重试",
    "session": "本次启动",
    "systemSettings": {
      "battery": "打开电池设置",
      "login_items": "打开登录项设置",
      "network": "打开网络设置",
      "notifications": "打开通知设置"
    },
    "total": "合计",
    "unavailable": "不可用",
    "unknown": "未知",
    "unknownUser": "未知用户",
    "unnamedProcess": "未命名进程",
    "warmup": "预热中",
    "write": "写入"
  },
  "companion": {
    "action": {
      "attention": "看看原因",
      "loading": "打开日常助手",
      "normal": "我遇到了问题",
      "observing": "查看当前状态",
      "urgent": "现在查看"
    },
    "collapse": "收起 Robin",
    "dragHint": "拖动 Robin 移动；双击打开主窗口；悬停查看状态；右键打开菜单",
    "expand": "打开 Robin",
    "hide": "隐藏 Robin",
    "kicker": "Robin",
    "menu": "Robin 菜单",
    "quickClean": {
      "action": "快速清理"
    },
    "reason": "{{resource}}最近值得留意，可以打开主窗口看看原因。",
    "recovering": "指标已回落，我再观察一会儿确认它是否恢复。"
  },
  "daily": {
    "applications": {
      "calmDescription": "正常运行的应用仍可按需展开查看，但不会占据首屏。",
      "calmTitle": "现在没有应用需要处理",
      "description": "先看值得留意的应用，需要时再展开查看。",
      "empty": "没有匹配的应用",
      "evidence": {
        "cpu": "处理能力",
        "disk": "文件读写",
        "memory": "内存"
      },
      "hideAll": "收起普通应用",
      "kicker": "正在运行",
      "level": {
        "critical": "影响明显",
        "high": "影响较大",
        "low": "运行正常",
        "moderate": "有些影响"
      },
      "ordinary": "普通应用",
      "reason": {
        "balanced": "目前没有某一项资源特别突出。",
        "cpu": "{{name}} 当前主要在使用处理能力。",
        "disk": "{{name}} 当前正在频繁读写文件。",
        "memory": "{{name}} 当前主要占用较多内存。"
      },
      "refresh": "更新列表",
      "refreshing": "正在更新…",
      "requestClose": "请求 {{name}} 退出",
      "restart": "重新启动 {{name}}",
      "restartComplete": "{{name}} 已正常退出并重新打开。",
      "restartStillRunning": "{{name}} 仍在运行，因此没有重复打开。",
      "restartUnavailable": "CoreRobin 暂时无法安全地重新启动 {{name}}。",
      "search": "搜索应用",
      "showAll": "查看全部 {{count}} 个普通应用",
      "snapshotClear": "没有应用持续影响电脑",
      "snapshotFound": "有 {{count}} 个应用值得先看看",
      "snapshotTime": "更新于 {{time}}",
      "system": "系统组件",
      "systemSafety": "这是系统组件，只展示依据，不建议直接结束。",
      "title": "哪些应用正在影响电脑",
      "viewEvidence": "查看详细依据"
    },
    "attention": {
      "application": {
        "critical": "正在大量使用资源，可能明显影响流畅度。",
        "high": "持续使用较多资源，可能影响流畅度。",
        "low": "当前影响较低。",
        "moderate": "正在使用一些电脑资源。",
        "title": "{{name}} 现在影响较大"
      },
      "battery": {
        "description": "如果还要继续使用一段时间，建议准备连接电源。",
        "title": "剩余电量不多"
      },
      "count": "{{count}} 项",
      "emptyDescription": "CoreRobin 会继续在后台留意持续变化。",
      "emptyTitle": "现在没有需要处理的事",
      "kicker": "现在",
      "open": "看看原因",
      "priority": "现在最值得留意",
      "recovering": "正在确认恢复",
      "sleep": {
        "description": "退出应用或暂停相关任务后通常会恢复。",
        "title": "{{name}} 正在阻止自动休眠"
      },
      "temperature": {
        "description": "减少高负荷任务并保持通风，通常会逐渐恢复。",
        "title": "电脑温度有些高"
      },
      "title": "值得留意的情况",
      "viewApplications": "看看哪些应用正在运行"
    },
    "checks": {
      "battery": "电池",
      "label": "电脑状态概览",
      "space": "空间",
      "speed": "速度",
      "temperature": "温度",
      "thisComputer": "这台电脑"
    },
    "companion": {
      "checking": "正在检查",
      "name": "Robin"
    },
    "guide": {
      "back": "返回首页",
      "checkAgain": "重新检查",
      "checkingAgain": "检查中…",
      "checkup": {
        "description": "把最新状态整理成一个主结论；没有足够依据时会继续观察。",
        "kicker": "日常检查",
        "normalDescription": "没有发现应用持续占用、真实内存压力或空间不足，现在不用做任何事。",
        "normalTitle": "现在很顺畅",
        "observingDescription": "还需约 {{seconds}} 秒，短暂打开应用不会被说成持续问题。",
        "observingKicker": "正在观察",
        "observingTitle": "再看一会儿，避免误判",
        "openPriority": "看看这件事",
        "priorityKicker": "最值得先看",
        "title": "看看电脑现在怎么样"
      },
      "heat": {
        "description": "分别检查温度、电池和阻止休眠的应用，不把单个读数说成硬件故障。",
        "kicker": "温度与电量检查",
        "requestClose": "请求 {{name}} 退出",
        "result": {
          "battery": {
            "description": "当前读数只能说明电量偏低；如果下降速度仍异常，可以继续观察正在运行的应用。",
            "title": "剩余电量已经不多"
          },
          "normal": {
            "description": "温度、电量和自动休眠目前没有提供需要处理的证据。",
            "title": "没有发现持续的发热或休眠问题"
          },
          "sleep": {
            "description": "它可能增加待机耗电；退出应用或暂停相关任务后通常会恢复。",
            "title": "{{name}} 正在让电脑保持唤醒"
          },
          "temperature": {
            "description": "先暂停高负荷任务并保持通风；温度恢复后再判断是否仍有问题。",
            "title": "电脑现在有些热"
          },
          "unknown": {
            "description": "温度、电池和休眠数据都不可用，因此不能判断是否存在发热或耗电问题。",
            "title": "暂时没有足够的设备状态"
          }
        },
        "sleepBlocked": "{{name}} 正在保持电脑唤醒",
        "sleepClear": "可以正常自动休眠",
        "sleepDescription": "退出应用或暂停相关任务后通常会恢复。",
        "sleepLabel": "自动休眠",
        "title": "看看为什么发热或耗电快",
        "viewApplications": "看看当前影响较大的应用"
      },
      "network": {
        "activeConnections": "活动连接",
        "activeTitle": "现在有网络活动",
        "checkingDescription": "连接扫描使用独立的低频命令，不影响系统主采样。",
        "checkingKicker": "正在读取",
        "checkingTitle": "正在获取活动连接",
        "connections": "{{count}} 条活动连接",
        "currentTraffic": "当前总流量",
        "description": "CoreRobin 会读取当前流量和活动连接，但不会在没有证据时把网络变慢归咎于某个应用。",
        "kicker": "网络检查",
        "quietTitle": "现在没有明显的网络活动",
        "resultDescription": "这只能说明当前活动情况；网速慢也可能来自路由器、运营商或远端服务。",
        "title": "看看网络现在发生了什么",
        "unknownDescription": "当前流量或连接列表不可用，因此不能判断网络是否正常。",
        "unknownTitle": "暂时没有足够的网络信息"
      },
      "professional": "查看完整指标和进程",
      "result": "检查结果",
      "safety": "CoreRobin 只提出有依据的建议，任何系统操作仍需要你确认。",
      "slow": {
        "applicationExplanation": "{{name}} 的持续活动与当前问题时间一致。",
        "description": "先观察持续变化，再告诉你最可能的原因和安全下一步。",
        "kicker": "流畅度检查",
        "likelyCause": "最可能相关的应用",
        "normalDescription": "如果你仍然觉得卡顿，可以查看当前应用；CoreRobin 不会在没有证据时猜测原因。",
        "normalTitle": "没有发现持续的资源压力",
        "observingDescription": "还需约 {{seconds}} 秒；CoreRobin 不会把打开网页或启动应用的一瞬间当成故障。",
        "observingKicker": "正在观察",
        "observingTitle": "先确认这不是一次短暂变忙",
        "requestClose": "请求 {{name}} 正常退出",
        "title": "找出电脑变慢的原因",
        "viewApplications": "查看当前应用"
      },
      "space": {
        "cachedScan": "已有完整扫描",
        "description": "先确认剩余空间，再决定是否进行完整文件分析。",
        "kicker": "空间检查",
        "lowDescription": "建议找出大文件和可回收内容，但不需要盲目删除系统缓存。",
        "lowTitle": "只剩 {{free}} 可用",
        "noScan": "尚未扫描文件",
        "normalDescription": "空间目前不紧张；只有你确实想整理文件时才需要扫描。",
        "normalTitle": "还有 {{free}} 可用",
        "openScan": "打开扫描结果",
        "reclaimable": "约 {{size}} 可优先核对",
        "scanExplanation": "完整扫描会生成可交互空间图，不会自动删除。",
        "startScan": "开始空间分析",
        "title": "看看空间是否真的不够",
        "unknownDescription": "系统没有提供可靠的容量信息，CoreRobin 不会把未知状态当成空间充足。",
        "unknownTitle": "暂时无法读取主要磁盘",
        "viewSpace": "查看空间概况"
      },
      "startup": {
        "description": "只优先列出可恢复的第三方登录项，系统服务保持只读。",
        "kicker": "登录速度检查",
        "resultDescription": "停用只是阻止下次自动启动，不会卸载应用。",
        "resultTitle": "先看真正值得评估的项目",
        "title": "看看哪些应用会随开机启动"
      },
      "viewEvidence": "为什么这样判断"
    },
    "home": {
      "checkNow": "检查一下",
      "checkedAt": "{{time}} 更新",
      "checking": "检查中…",
      "checkingSummary": "最新状态会直接汇入这里；如果还需要持续观察，Robin 会明确告诉你。",
      "checkingTitle": "Robin 正在看看电脑的近况",
      "haveProblem": "我遇到了问题",
      "kicker": "电脑状态伙伴",
      "localOnly": "状态和历史都保存在本机",
      "professional": "查看详细数据",
      "storage": {
        "available": "可用",
        "kicker": "磁盘存储",
        "open": "打开存储详情",
        "summary": "已用 {{used}}，共 {{total}}"
      },
      "viewDiagnosis": "查看检查结果",
      "viewPriority": "看看这件事"
    },
    "incident": {
      "causeMayHaveChanged": "应用状态可能已经变化，操作只会基于最新检查提供。",
      "observedCause": "触发时主要相关",
      "phase": {
        "active": "仍在发生",
        "recovering": "正在确认恢复",
        "resolved": "已经恢复"
      },
      "recoveringDescription": "最新指标已经回落，CoreRobin 正在继续观察，确认它不是一次短暂波动。",
      "resolvedDescription": "这项情况已经稳定恢复，现在不需要处理；触发时的证据仍保留在这里。",
      "sleepDuration": "已持续约 {{minutes}} 分钟",
      "timeline": "{{startedAt}} 确认 · 最近一次命中 {{lastSeenAt}}",
      "viewCurrentNetwork": "查看当前网络状态"
    },
    "intents": {
      "checkup": {
        "description": "从当前状态中找出最值得留意的一件事",
        "title": "检查一下"
      },
      "description": "不需要先理解 CPU 或内存，选择最接近你感受的情况。",
      "heat": {
        "description": "检查温度、电池和阻止休眠的应用",
        "title": "发热或耗电快"
      },
      "kicker": "从问题开始",
      "network": {
        "description": "看看当前流量和连接是否能提供线索",
        "title": "网络好像有问题"
      },
      "slow": {
        "description": "找出持续影响速度的应用或资源",
        "title": "电脑变慢了"
      },
      "space": {
        "description": "确认还剩多少，并找到真正占空间的内容",
        "title": "空间不够"
      },
      "startup": {
        "description": "看看哪些第三方应用会随登录启动",
        "title": "开机太慢"
      },
      "title": "你想解决什么？"
    },
    "more": {
      "description": "这些功能不会占据日常首页，需要时再打开。",
      "history": {
        "description": "查看资源趋势、提醒和恢复记录",
        "title": "完整历史"
      },
      "kicker": "按需使用",
      "language": "界面语言",
      "network": {
        "description": "查看接口、流量和活动连接详情",
        "title": "网络诊断"
      },
      "professional": "专业模式",
      "professionalDescription": "查看完整指标、进程树和更多详情",
      "settings": {
        "description": "语言、通知、历史保留和采样偏好",
        "title": "设置"
      },
      "startup": {
        "description": "查看和停用可恢复的第三方登录项",
        "title": "开机项目"
      },
      "title": "更多工具与设置"
    },
    "nav": {
      "applications": "应用",
      "cleanupQuick": "快速清理",
      "cleanupScan": "磁盘扫描",
      "home": "电脑状态",
      "more": "更多",
      "records": "回顾",
      "settings": "设置",
      "solve": "帮我解决",
      "space": "空间",
      "today": "电脑状态"
    },
    "recheck": {
      "already_exited": "应用在操作前已经退出，最新状态已重新读取。",
      "checkingDescription": "稍等一下，CoreRobin 正在读取变化并重新整理检查结果。",
      "checkingTitle": "正在汇总最新状态",
      "checkup": {
        "observingDescription": "最新状态已经读取，但持续问题还需要再观察一会儿。"
      },
      "completed": "检查完成",
      "completedAt": "{{time}}",
      "exited": "应用已经退出，最新状态已重新读取。",
      "facts": {
        "currentReading": "当前读数",
        "notFound": "未发现",
        "observedFor": "持续观察",
        "seconds": "{{count}} 秒",
        "startupTotal": "启动项总数",
        "sustainedPressure": "持续资源压力",
        "worthReviewing": "值得核对"
      },
      "heat": {
        "attention": {
          "description": "下面列出了刚刚读取的温度、电池和休眠情况。",
          "title": "有一项设备状态值得留意"
        },
        "normal": {
          "description": "这三项目前没有发现需要处理的情况。",
          "title": "温度、电池和休眠状态都很平稳"
        },
        "observing": {
          "description": "CoreRobin 会保持未知状态，不会把缺少的数据判断为正常。",
          "title": "部分设备状态暂时无法读取"
        },
        "urgent": {
          "description": "先减少高负荷任务或连接电源，再重新检查一次。",
          "title": "建议尽快处理当前设备状态"
        }
      },
      "live": {
        "checkup": {
          "description": "状态、连接和开机项目会各自返回真实结果，不使用表演性倒计时。",
          "title": "Robin 正在检查这台电脑"
        },
        "heat": {
          "description": "缺少的数据会保持未知，不会被误判为正常。",
          "title": "正在读取温度、电量与休眠状态"
        },
        "network": {
          "description": "低频读取流量和活动连接，不持续追踪每一条连接。",
          "title": "正在读取当前网络活动"
        },
        "slow": {
          "description": "读取最新状态；持续问题会继续观察，短暂变忙不会被当成故障。",
          "title": "正在观察电脑为什么会卡"
        },
        "space": {
          "description": "这里只读取磁盘容量，不会在后台启动耗时的完整文件扫描。",
          "title": "正在确认剩余空间"
        },
        "startup": {
          "description": "系统项目保持只读，只整理可以安全评估的第三方应用。",
          "title": "正在读取开机项目"
        }
      },
      "loadingKicker": "正在扫描这台电脑",
      "outcomeTitle": {
        "already_exited": "应用之前已经退出",
        "exited": "应用已经退出",
        "still_running": "应用仍在运行"
      },
      "refreshed": "最新状态已经读取完成。",
      "resultKicker": "最新状态已同步",
      "slow": {
        "observingDescription": "最新数据已经读取，但还需要继续观察，避免把一次短暂变忙当成持续问题。"
      },
      "startup": {
        "unavailableDescription": "系统还没有返回可用的启动项结果，可以稍后再试一次。",
        "unavailableTitle": "暂时无法读取启动项"
      },
      "steps": {
        "compare": "对比刚才变化",
        "read": "读取最新状态",
        "update": "整理检查结果"
      },
      "still_running": "应用仍在运行，CoreRobin 没有继续强制处理。",
      "title": "重新检查完成",
      "updated": "刚刚更新"
    },
    "records": {
      "description": "持续出现的电脑变化，以及你确认执行的操作和结果，都会整理在这里。",
      "duration": "约 {{minutes}} 分钟",
      "emptyDescription": "以后出现持续卡顿、内存压力或空间不足时，会在这里留下容易理解的记录。",
      "emptyTitle": "最近一直很平稳",
      "groups": {
        "earlier": "更早",
        "today": "今天",
        "yesterday": "昨天"
      },
      "kicker": "最近发生的变化",
      "showLess": "收起较早记录",
      "showMore": "查看全部 {{count}} 条记录",
      "title": "处理前后，都有记录"
    },
    "review": {
      "description": "把今天的异常、恢复和你执行过的操作整理成一份可核对的结果。",
      "evidence": "今天记录的主要资源来源是 {{name}}；整机峰值 CPU {{cpu}}、内存 {{memory}}。",
      "kicker": "本机 · 今天",
      "metricNames": {
        "cpu": "CPU",
        "memory": "内存"
      },
      "metrics": {
        "actions": "已执行操作",
        "events": "值得留意",
        "network": "网络变化",
        "resolved": "已经恢复"
      },
      "noResults": "完成退出应用、清理或启动项调整后，核对结果会显示在这里。",
      "observedMetric": "{{metric}}：操作后观察到 {{before}} → {{after}} · {{effect}}",
      "open": "打开对应功能",
      "outcomes": {
        "cleanup": "选择 {{selected}} 项，成功处理 {{succeeded}} 项，跳过 {{skipped}} 项，实际释放 {{size}}。",
        "startupChanged": "系统已重新检查并确认启动状态已变更。",
        "startupNotConfirmed": "暂时无法确认启动状态已经变更。",
        "uninstallKept": "尚未确认应用本体已移除；成功处理 {{succeeded}} 个残留，{{failed}} 个未完成。",
        "uninstallRemoved": "应用本体已移除；成功处理 {{succeeded}} 个残留，{{failed}} 个未完成。",
        "updateConfirmed": "应用已重启，并确认当前版本为 {{version}}。",
        "updateNotInstalled": "尚未确认更新已安装。",
        "updateReady": "更新已下载并安装，仍需重启应用完成版本切换。",
        "volumeEjected": "系统已确认该存储卷完成卸载。",
        "volumeNotEjected": "系统未能确认该存储卷已卸载。"
      },
      "resultsDescription": "只比较操作前后的本机采样，不把相关性说成因果。",
      "resultsTitle": "处理效果",
      "status": {
        "active": "仍有 {{count}} 件事值得处理",
        "calm": "今天没有持续异常",
        "handled": "今天的操作已完成并留下结果",
        "settled": "今天出现过波动，目前都已恢复"
      },
      "title": "今日回顾"
    },
    "settings": {
      "companionAlwaysOnTop": "始终显示在其他窗口上方",
      "companionAlwaysOnTopDescription": "关闭后 Robin 仍会留在桌面，但可能被其他窗口遮住",
      "companionShowOnStartup": "让 Robin 常驻桌面",
      "companionShowOnStartupDescription": "开启后立即显示，并在下次启动时继续出现",
      "description": "这里只保留日常会用到的偏好；专业采样和阈值设置留在专业模式。",
      "history": "保留最近记录",
      "historyDescription": "关闭后不再把资源变化保存到本机",
      "kicker": "日常助手设置",
      "language": "界面语言",
      "languageDescription": "随时选择适合你的界面语言",
      "launchAtLogin": "登录时启动",
      "launchAtLoginDescription": "登录系统后在后台启动，不主动弹出主窗口",
      "notificationStatus": {
        "denied": "提醒权限已关闭",
        "disabled": "开启后会请求系统权限",
        "ready": "只提醒持续出现的重要变化",
        "requesting": "正在等待系统权限",
        "unavailable": "当前系统不支持桌面提醒"
      },
      "notifications": "桌面提醒",
      "openProfessional": "进入专业模式",
      "professional": "专业模式",
      "professionalDescription": "查看完整指标、进程树、网络连接和高级设置",
      "reduceMotion": "减少动态效果",
      "reduceMotionDescription": "停用持续旋转、呼吸和位移动画",
      "showDockIcon": "在 Dock 中显示应用",
      "showDockIconDescription": "让 CoreRobin 显示在 Dock 和应用切换器；如只想从状态栏访问可关闭",
      "textSize": "文字大小",
      "textSizeDescription": "放大日常页面和列表文字",
      "textSizeOptions": {
        "comfortable": "标准",
        "large": "大号"
      },
      "title": "让 Robin 按你的方式工作"
    },
    "shell": {
      "label": "日常模式",
      "localOnly": "分析只在本机进行",
      "openProfessional": "进入专业模式"
    },
    "solve": {
      "applications": {
        "description": "只先展示最值得处理的几个应用",
        "title": "哪些应用最影响电脑"
      },
      "battery": {
        "description": "检查电量、温度和阻止休眠的应用",
        "title": "电池掉得很快"
      },
      "checkup": {
        "description": "读取最新状态并给出一个主结论",
        "title": "我只是想检查一下"
      },
      "description": "不需要先判断是处理器、内存还是网络，选最接近你感受的情况。",
      "footer": "CoreRobin 不会为了显得有用而猜测原因；没有足够依据时会继续观察。",
      "heat": {
        "description": "看看温度和持续繁忙的应用",
        "title": "风扇一直很响"
      },
      "kicker": "从你的感受开始",
      "network": {
        "description": "读取当前流量与活动连接，寻找可用线索",
        "title": "网络好像有问题"
      },
      "otherProblems": "其他情况",
      "recommended": "根据当前状态推荐",
      "slow": {
        "description": "找出持续让电脑变慢的应用或活动",
        "title": "电脑有点卡"
      },
      "space": {
        "description": "先确认剩余空间，再决定是否扫描文件",
        "title": "空间快不够了"
      },
      "startup": {
        "description": "看看哪些第三方应用会自动打开",
        "title": "开机越来越慢"
      },
      "title": "你遇到了什么情况？"
    },
    "space": {
      "attention": {
        "description": "还剩 {{free}}，可以先找出真正占空间的内容。",
        "title": "可用空间不多了"
      },
      "available": "可用",
      "capacity": "主要磁盘容量",
      "checkAgain": "重新检查",
      "kicker": "这台电脑的空间",
      "normal": {
        "description": "还剩 {{free}}，暂时不需要为了数字而清理。",
        "title": "目前还有足够空间"
      },
      "professional": "查看磁盘详细数据",
      "scan": {
        "cached": "结果来自 {{time}} 的完整扫描；打开后会核对当前目录变化。",
        "description": "扫描文件名、大小等元数据，生成可以下钻的空间图。",
        "found": "发现约 {{size}} 可优先核对",
        "notYet": "还没有分析过文件",
        "open": "打开空间清理",
        "ready": "已有最近扫描结果",
        "start": "开始空间分析",
        "title": "看看空间都去了哪里"
      },
      "showDetails": "容量详情",
      "unknown": {
        "description": "系统没有提供可用的磁盘容量信息。",
        "title": "暂时无法读取空间"
      },
      "usage": "当前已使用 {{percent}}%",
      "used": "已使用"
    },
    "status": {
      "attention": {
        "short": "有些情况值得留意",
        "summary": "CoreRobin 已经整理好原因和下一步，你可以直接按建议处理。",
        "title": "有 {{count}} 项情况值得留意"
      },
      "normal": {
        "short": "运行平稳",
        "summary": "目前没有发现需要你处理的问题。",
        "title": "电脑运行平稳"
      },
      "observing": {
        "short": "正在了解状态",
        "summary": "再观察一会儿，避免把短暂波动误判成问题。",
        "title": "正在了解这台电脑"
      },
      "urgent": {
        "short": "建议尽快看看",
        "summary": "先核对原因，再选择合适的处理方式。",
        "title": "有 {{count}} 项情况建议尽快看看"
      }
    },
    "story": {
      "active": "正在发生",
      "cause": "当时主要与 {{name}} 有关。",
      "cpu": {
        "active": "从 {{time}} 起，电脑已持续繁忙约 {{minutes}} 分钟",
        "recovered": "{{time}} 附近曾繁忙约 {{minutes}} 分钟，现在已经恢复"
      },
      "emptyDescription": "出现持续的资源压力后，这里会用人话记录发生时间和恢复情况。",
      "emptyTitle": "最近一直很平稳",
      "kicker": "最近",
      "memory": {
        "active": "从 {{time}} 起，内存压力已持续约 {{minutes}} 分钟",
        "recovered": "{{time}} 附近曾出现内存压力，现在已经恢复"
      },
      "recovered": "已经恢复",
      "title": "最近发生了什么",
      "viewAll": "查看全部记录",
      "volume": {
        "active": "从 {{time}} 起，可用空间一直偏少",
        "recovered": "{{time}} 附近的空间不足提醒已经恢复"
      }
    },
    "topbar": {
      "thisComputer": "这台电脑",
      "thisMac": "这台 Mac"
    },
    "weekly": {
      "actions": "已处理",
      "anomalies": "异常",
      "averages": "平均 CPU {{cpu}} · 内存 {{memory}}",
      "comparison": {
        "fewer": "今天少记录到 {{count}} 次异常。",
        "more": "今天多记录到 {{count}} 次异常。",
        "same": "今天同样记录到 {{count}} 次异常。"
      },
      "comparisonTitle": "与昨天相比",
      "coverage": "已有 {{days}} 天采样 · 七天日均 {{average}} 次异常",
      "description": "分别比较已记录的异常与处理结果，不把无关指标拼成健康分数。",
      "improvementObserved": "操作后 {{metrics}} 下降 · {{time}}",
      "improvements": "观察到改善",
      "improvementsTitle": "操作后观察到的改善",
      "kicker": "七天回顾",
      "noImprovements": "目前还没有哪项操作具备足够的前后采样来确认改善。",
      "notification": "每周提醒",
      "notificationBody": "过去 7 天记录到 {{anomalies}} 次异常、{{improvements}} 项操作后改善。打开回顾可查看依据。",
      "notificationTitle": "CoreRobin 每周回顾已准备好",
      "notificationUnavailable": "请先在设置中开启桌面通知，再启用本机每周提醒。",
      "sevenDays": "过去 7 天",
      "title": "昨天与这一周",
      "today": "今天",
      "yesterday": "昨天"
    }
  },
  "diagnosis": {
    "actionDialog": {
      "bestEffortIdentity": "CoreRobin 会在执行前再次确认进程；如果目标已经变化，不会继续操作。",
      "confirm": "确认请求 {{name}} 退出",
      "confirmRestart": "重新启动 {{name}}",
      "description": "CoreRobin 将向应用发送正常结束请求；这是温和处理，不是强制结束。",
      "restartDescription": "CoreRobin 会先请求应用正常退出，再重新打开已经核验的应用包。",
      "restartTitle": "重新启动 {{name}}？",
      "riskDescription": "应用是否显示保存提示取决于它自身；未保存内容仍可能丢失。",
      "riskTitle": "先保存正在编辑的内容",
      "safeDescription": "这项操作只请求当前应用结束运行，不会清理它的数据。",
      "safeTitle": "不会删除应用或文件",
      "stableIdentity": "操作只会作用于你刚刚选择的进程，执行前还会再次确认。",
      "title": "请求 {{name}} 退出？"
    },
    "actions": {
      "inspectApp": "查看 {{name}}",
      "network": "查看网络活动",
      "processes": "查看进程证据",
      "storage": "查看存储空间"
    },
    "categories": {
      "cpu": "处理器",
      "disk_io": "磁盘活动",
      "memory": "内存压力",
      "network": "网络活动",
      "storage": "剩余空间"
    },
    "checkedLabel": "智能诊断检查项",
    "collapse": "收起诊断",
    "connectionScan": {
      "loading": "正在低频扫描活动连接…",
      "unavailable": "活动连接暂时无法扫描；网络流量检查仍然有效。"
    },
    "culprit": {
      "summary": "{{name}} 最突出：{{metric}}，合并统计 {{count}} 个相关进程。",
      "system": "这是系统组件或受保护进程，不建议直接结束。"
    },
    "duration": "持续 {{seconds}} 秒",
    "empty": {
      "healthy": {
        "description": "如果体感仍然卡顿，可以继续查看进程列表和五分钟趋势。",
        "title": "五项检查均未发现明显问题"
      },
      "observing": {
        "description": "空间不足等即时问题仍会立即提示；持续占用需要多观察一会儿。",
        "title": "正在建立稳定基线"
      }
    },
    "evidence": {
      "cpu": "CPU {{value}} · {{duration}}",
      "disk": "{{value}} · {{duration}}",
      "memory": "内存 {{value}} · 交换 {{swap}}",
      "network": "{{value}} · {{count}} 个连接",
      "storage": "已用 {{value}} · 剩余 {{available}}"
    },
    "explain": "查看诊断结果",
    "findings": {
      "busy_disk": {
        "description": "大量读写会让应用启动、保存文件和系统响应变慢。",
        "title": "磁盘持续忙碌"
      },
      "high_network": {
        "description": "下载、同步、视频或大量连接可能占用带宽并影响其他应用。",
        "title": "网络活动明显增多"
      },
      "low_storage": {
        "description": "剩余空间太少会影响更新、缓存和临时文件，也可能拖慢系统。",
        "title": "{{resource}} 空间不足"
      },
      "memory_pressure": {
        "description": "系统已经开始依赖交换空间，切换应用和打开窗口可能出现停顿。",
        "title": "可用内存不足"
      },
      "sustained_cpu": {
        "description": "长时间高占用会让应用响应变慢、风扇加速，并增加耗电。",
        "title": "处理器持续繁忙"
      }
    },
    "kicker": "智能诊断",
    "networkBoundary": "这里只表示流量或连接数量较高，不代表发现了恶意程序。",
    "recommendations": {
      "actionUnavailable": "这个应用当前无法安全核对或处理，CoreRobin 没有执行任何操作。",
      "inspectEvidence": "先看应用证据",
      "inspect_process": {
        "action": "查看详细证据",
        "description": "CoreRobin 当前不提供直接处理按钮；先确认应用身份、资源变化和系统保护原因。",
        "title": "先查看详细证据"
      },
      "open_cleanup": {
        "action": "打开清理助手",
        "description": "先预览空间去向；拖入清理篮的内容只有在明确确认后才会移到废纸篓或永久删除。",
        "title": "建议打开空间清理助手"
      },
      "open_network": {
        "action": "查看网络活动",
        "description": "查看协议、状态和连接对象，确认这是下载、同步还是暂时无法解释的流量。",
        "title": "建议核对联网活动"
      },
      "preparing": "正在核对…",
      "request_close": {
        "action": "请求退出 {{name}}",
        "description": "这是优先级最高的温和处理方式。CoreRobin 会先核对进程身份并显示确认窗口，不会直接强制结束。",
        "title": "建议先请求 {{name}} 退出"
      },
      "safety": {
        "confirmation": "需要确认",
        "protected": "系统保护",
        "safe": "安全入口"
      }
    },
    "safety": "CoreRobin 不会自动操作；推荐动作仍需你确认，强制结束只保留在专业模式。",
    "severity": {
      "attention": "建议关注",
      "urgent": "影响明显"
    },
    "status": {
      "attention": {
        "summary": "发现 {{count}} 个可能影响使用体验的问题，可以展开查看原因。",
        "title": "电脑可能正在变慢"
      },
      "healthy": {
        "summary": "没有发现持续占用、内存压力、空间不足或异常大流量。",
        "title": "目前运行正常"
      },
      "observing": {
        "summary": "再观察约 {{seconds}} 秒，避免把一瞬间的波动误判成问题。",
        "title": "正在了解这台电脑"
      },
      "urgent": {
        "summary": "发现 {{count}} 个影响较明显的问题，CoreRobin 会先带你核对证据。",
        "title": "有问题需要尽快处理"
      }
    },
    "thisDisk": "系统磁盘"
  },
  "format": {
    "days": "{{count}} 天",
    "hours": "{{count}} 小时",
    "minutes": "{{count}} 分钟",
    "seconds": "{{count}} 秒",
    "unknownError": "发生了未知错误。",
    "unsupportedSchema": "不支持的数据版本：{{version}}"
  },
  "history": {
    "actions": {
      "cleanupFailed": "{{count}} 项未完成",
      "cleanupResult": "处理 {{count}} 项，释放 {{size}}",
      "clear": "清除操作记录",
      "count": "最近 {{count}} 项",
      "description": "记录你确认执行的操作，并在可能时核对是否生效。",
      "emptyDescription": "关闭应用、清理文件或管理启动项后，结果会显示在这里。",
      "emptyTitle": "还没有执行过操作",
      "eyebrow": "你执行过的操作",
      "kind": {
        "application_uninstall": "卸载应用",
        "application_update": "安装应用更新",
        "cleanup_delete": "清理文件",
        "process_close": "正常退出应用",
        "process_force_quit": "强制结束应用",
        "process_restart": "重新启动应用",
        "startup_disable": "停用启动项",
        "startup_enable": "恢复启动项",
        "volume_eject": "推出可移除卷"
      },
      "open": "查看",
      "retry": "重试",
      "saved": "{{count}} 项已保存操作",
      "status": {
        "cancelled": "已取消",
        "failed": "未完成",
        "interrupted": "意外中断",
        "partial": "部分完成",
        "running": "正在执行",
        "succeeded": "已完成"
      },
      "target": {
        "application": "应用名称未保存",
        "files": "已选择的文件",
        "startup": "启动项名称未保存"
      },
      "title": "操作与结果",
      "verification": {
        "not_confirmed": "暂时无法确认最终状态",
        "pending": "正在核对结果",
        "verified": "已重新核对系统状态"
      }
    },
    "alerts": {
      "active": "{{count}} 个活动告警",
      "all": "全部",
      "description": "资源持续达到“偏高”阈值后触发；恢复回差与冷却机制会减少尖峰和重复事件。",
      "emptyDescription": "短暂尖峰不会产生记录；持续超限或恢复后会在这里显示。",
      "emptyTitle": "暂无告警事件",
      "eventCount": "{{count}} 条事件",
      "eyebrow": "本机事件记录",
      "filters": "告警资源筛选",
      "normal": "当前正常",
      "recovered": "已恢复",
      "recoveredDetail": "已回落到 {{value}}%，本次告警持续 {{duration}}。",
      "savedEvents": "{{count}} 个已保存事件",
      "severity": {
        "critical": "严重",
        "high": "偏高"
      },
      "title": "告警与恢复事件",
      "triggeredDetail": "{{value}}%，高于 {{threshold}}% 已持续 {{duration}}。",
      "volume": "卷占用"
    },
    "applicationImpact": {
      "boundary": "不保存命令或文件路径；应用名称仍受单独的隐私开关控制。",
      "description": "可选保存五分钟应用聚合，帮助判断是谁反复占用 CPU、内存或磁盘。",
      "disabledDescription": "开启后只在本机保存稳定应用身份和聚合指标。",
      "disabledTitle": "应用归因尚未开启",
      "enable": "保留应用影响历史",
      "explanation": "{{time}} 左右，{{name}} 在该时段影响最高，平均 CPU {{cpu}}、内存 {{memory}}。",
      "eyebrow": "应用归因",
      "hours1": "1 小时",
      "hours168": "7 天",
      "hours24": "24 小时",
      "learningDescription": "收集到足够的五分钟采样后会显示排名。",
      "learningTitle": "正在建立应用历史",
      "peakCpu": "CPU 峰值 {{value}}",
      "range": "应用历史范围",
      "relativeActivity": "相对活动",
      "storageFailed": "历史仍可查看，但新采样暂时无法保存；CoreRobin 会自动重试。",
      "storageLoading": "正在打开私有历史存储…",
      "storagePending": "等待首次写入",
      "storageReady": "已保存到本机 · {{size}} · 最近写入 {{time}}",
      "timeline": "应用影响趋势",
      "timelineHint": "点击柱形查看对应时段",
      "title": "哪些应用影响过这台电脑"
    },
    "archiveDescription": "跨重启查看资源长期变化，以及持续超限与恢复事件。",
    "archiveTitle": "历史",
    "averageCpu": "平均 CPU",
    "averageMemory": "平均内存",
    "baseline": {
      "change": "比平时{{direction}} {{value}}%",
      "collecting": "正在积累基线",
      "coverage": "{{days}} 个可比日期 · {{count}} 个采样",
      "elevated": {
        "description": "有 {{count}} 项指标明显高于过去七天相同时段。",
        "title": "和这台电脑平时不太一样"
      },
      "eyebrow": "这台电脑的基线",
      "higher": "高",
      "learning": {
        "description": "需要更多相同时段采样，才能和这台电脑自己做比较。",
        "title": "正在学习这台电脑的日常状态"
      },
      "lower": "低",
      "metric": {
        "battery": "电池消耗",
        "cpu": "CPU",
        "disk": "磁盘吞吐",
        "memory": "内存",
        "network": "网络吞吐",
        "temperature": "温度"
      },
      "partial": {
        "description": "部分指标已有足够的可比日期，其余指标会继续明确显示为学习中。",
        "title": "这台电脑的部分基线已经可用"
      },
      "typical": {
        "description": "当前可用指标没有出现明显偏离。",
        "title": "接近这台电脑平时的状态"
      }
    },
    "batterySessions": {
      "blockers": "阻止睡眠：{{names}}",
      "charge": "电量变化",
      "count": "{{count}} 次会话",
      "description": "从拔掉电源开始分段，使用本机聚合历史解释掉电速度、主要资源来源和阻止睡眠的应用。",
      "drainRate": "平均掉电",
      "duration": "{{minutes}} 分钟",
      "empty": "还没有积累出完整的电池使用会话。",
      "evidence": "可能的主要资源来源",
      "eyebrow": "电池使用时间轴",
      "noApplicationEvidence": "未保存应用名称",
      "ongoing": "进行中",
      "title": "电池使用会话"
    },
    "chartLabel": "CPU {{cpu}}%，内存 {{memory}}%",
    "chartRange": "图表时间范围",
    "clearSaved": "清除已保存数据",
    "controls": "历史记录设置",
    "dataCompleteness": "数据完整度 {{percent}}%",
    "emptyDescription": "收到第一个有效采样后会显示趋势；启用本机保存后可跨重启保留。",
    "emptyTitle": "正在建立历史基线",
    "establishing": "正在建立趋势基线…",
    "export": {
      "description": "选择时间范围和指标，确认隐私内容后，将 CSV 或 JSON 文件保存到这台电脑。",
      "excluded": "始终不包含进程命令、完整文件路径和网络连接地址。",
      "eyebrow": "本地副本",
      "format": "文件格式",
      "includeNames": "包含应用名称",
      "includeNamesDescription": "默认关闭；关闭时应用身份会替换为 application-1 等匿名标签。",
      "localOnly": "文件只保存在本机，不会上传。",
      "metric": {
        "actions": "已完成操作",
        "applications": "应用影响",
        "cpu": "CPU",
        "disk": "磁盘",
        "events": "异常提醒",
        "memory": "内存",
        "network": "网络"
      },
      "metrics": "指标与记录",
      "preview": "{{from}} 至 {{to}}，共 {{count}} 行",
      "previewTitle": "隐私预览",
      "range": "时间范围",
      "ranges": {
        "168": "7 天",
        "24": "24 小时",
        "all": "全部记录"
      },
      "save": "保存导出文件",
      "saved": "历史数据已导出。",
      "title": "导出历史数据"
    },
    "fiveMinuteResolution": "5 分钟分辨率",
    "legend": "图表图例",
    "localArchive": "本机资源档案",
    "memory": "内存",
    "noRange": "尚无时间范围",
    "peakDisk": "磁盘峰值",
    "peakNetwork": "网络峰值",
    "privacyCollected": "记录整机资源快照、超限与恢复事件，以及你确认执行的操作类型、结果、数量和释放空间；应用或启动项名称只有在设置中单独允许后才会保存。",
    "privacyControl": "停用后不再写入新数据；已有记录会保留到过期或由你手动清除。",
    "privacyExcluded": "资源与操作历史不记录进程命令、用户、路径、文件名或连接地址；如果你单独开启“连接历史”，五分钟聚合数据可能在本机保存远端 IP、域名、端口和应用名。",
    "privacyEyebrow": "数据边界",
    "privacyLocal": "历史只保存在当前设备的 CoreRobin 私有存储中，不会上传或同步。",
    "privacyTitle": "隐私说明",
    "replay": {
      "actionImpact": {
        "improved": "操作后 15 分钟内系统压力有所下降",
        "increased": "操作后 15 分钟内系统压力有所上升",
        "insufficient": "后续样本不足，暂时无法比较效果",
        "not_applicable": "这项操作不适合用系统压力变化判断效果",
        "stable": "操作前后系统压力基本持平"
      },
      "alert": {
        "recovered": "资源压力恢复",
        "triggered": "资源压力开始"
      },
      "applicationEvidence": "{{from}}–{{to}}，{{applications}} 是已记录的主要资源来源；整机峰值达到 CPU {{cpu}}、内存 {{memory}}。",
      "description": "选择一个时段，关联资源变化、网络事件、应用归因以及你确认过的操作结果。",
      "empty": "这段时间没有告警、网络、应用关注或操作事件。",
      "evidenceTitle": "这段时间的证据",
      "eyebrow": "证据时间轴",
      "from": "开始",
      "hours1": "1 小时",
      "hours168": "7 天",
      "hours24": "24 小时",
      "leadingApplication": "{{application}} 在所选聚合中的平均 CPU 为 {{cpu}}，平均内存为 {{memory}}。",
      "network": {
        "direct_failure": "直连质量下降",
        "dns_failure": "DNS 质量下降",
        "interface_change": "网络接口发生变化",
        "sleep_gap": "睡眠期间暂停采样",
        "status_change": "网络状态发生变化"
      },
      "noApplicationEvidence": "这段时间未保存应用归因；整机峰值达到 CPU {{cpu}}、内存 {{memory}}。",
      "range": "回放范围",
      "title": "系统事件回放",
      "to": "结束",
      "watch": {
        "recovered": "应用关注规则恢复",
        "triggered": "应用关注规则触发"
      }
    },
    "resourceChart": "CPU 与内存",
    "resourceChartLabel": "历史 CPU 与内存趋势",
    "retention": "保留",
    "retentionDays": "{{count}} 天",
    "saveOnDevice": "在此设备保存聚合历史",
    "savedPoints": "{{count}} 个已保存点",
    "saving": "正在本机保存",
    "sessionOnly": "仅当前会话",
    "storage": {
      "failed": "历史保存已暂停；停留查看原因",
      "saved": "原生历史已保存 {{time}} · {{size}}",
      "waiting": "原生历史存储正在启动"
    },
    "stories": {
      "cause": "主要原因：{{name}} 当时占用最高",
      "count": "最近 {{count}} 件",
      "cpu": {
        "active": {
          "description": "处理器已高负荷运行 {{duration}}，峰值约 {{value}}%；电脑可能会卡顿、发热或更耗电。",
          "title": "电脑正在持续忙碌"
        },
        "guidance": "如果仍然觉得卡，可以到“应用”查看是谁影响最大；CoreRobin 不会自动关闭任何应用。",
        "recovered": {
          "description": "这次高负荷持续约 {{duration}}，峰值约 {{value}}%，之后已回到正常范围。",
          "title": "电脑曾忙了一阵，现在已经恢复"
        }
      },
      "description": "把成对的告警与恢复合并成一件事，用普通语言说明影响和结果。",
      "emptyDescription": "CoreRobin 会忽略短暂波动，只把持续影响电脑的情况整理在这里。",
      "emptyTitle": "最近没有值得担心的事情",
      "endedAt": "{{time}} 恢复",
      "eyebrow": "发生过什么",
      "happeningNow": "仍在发生",
      "inspectApplications": "查看峰值时的应用",
      "memory": {
        "active": {
          "description": "低可用内存和交换活动已持续 {{duration}}；切换应用时可能变慢。",
          "title": "可用内存正在变得紧张"
        },
        "guidance": "单纯“内存用得多”并不是问题；这里只记录低可用内存同时伴随明显交换活动的情况。",
        "recovered": {
          "description": "这次内存紧张持续约 {{duration}}，随后可用内存和交换活动恢复。",
          "title": "内存压力曾经升高，现在已经缓解"
        }
      },
      "peakedAt": "{{time}} 达到峰值 {{value}}%",
      "resolved": "已经恢复",
      "startedAt": "{{time}} 开始",
      "timeline": "事件时间线",
      "title": "电脑状态故事",
      "volume": {
        "active": {
          "description": "磁盘占用已持续高于提醒线 {{duration}}，当前最高约 {{value}}%。",
          "title": "磁盘剩余空间偏少"
        },
        "guidance": "可以先打开“清理”查看空间地图；任何文件处理都需要你确认。",
        "recovered": {
          "description": "磁盘空间曾紧张约 {{duration}}，现在已经回到提醒线以下。",
          "title": "磁盘空间压力已经缓解"
        }
      }
    },
    "summary": "历史摘要",
    "throughputChart": "磁盘与网络吞吐",
    "throughputChartLabel": "历史磁盘与网络吞吐趋势",
    "title": "资源趋势",
    "warmup": "预热",
    "watchRules": {
      "description": "记录你创建的提醒规则在本机触发和恢复的时间。",
      "privateApplication": "未保存应用名称",
      "recovered": "{{metric}} 恢复至 {{value}}{{unit}}",
      "savedEvents": "{{count}} 条关注事件",
      "title": "应用关注记录",
      "triggered": "{{metric}} 达到 {{value}}{{unit}}"
    }
  },
  "network": {
    "accumulated": "累计 {{value}}",
    "chartLabel": "网络接收 {{receive}}，发送 {{send}}",
    "collapseUnused": "收起未使用接口",
    "connectedInterfaces": "{{connected}} / {{total}} 个接口已连接",
    "connections": {
      "allConnections": "全部连接",
      "attributedSummary": "{{count}} 项有进程",
      "attribution": {
        "available": "系统可提供连接进程归属。",
        "partial": "系统权限可能导致部分连接无法关联进程。",
        "unavailable": "当前平台无法提供连接进程归属。"
      },
      "collecting": "正在采集本机连接…",
      "collection": "独立低频采集",
      "count": "{{count}} 项",
      "description": "每 {{seconds}} 秒更新一次；显示系统可报告的进程归属，权限不足时仍保留连接本身。",
      "empty": "当前筛选条件下没有连接。",
      "established": "已建立",
      "failure": "连接采集暂时失败：{{message}}",
      "filters": "连接筛选",
      "filtersLabel": {
        "all": "全部",
        "established": "已建立",
        "listen": "监听",
        "tcp": "TCP",
        "udp": "UDP"
      },
      "inspectProcess": "查看 {{name}} 的进程详情",
      "listening": "监听",
      "localAddress": "本地地址",
      "more": "显示更多（剩余 {{count}} 项）",
      "ownerUnavailable": "当前快照中不可用",
      "paused": "监控已暂停，上一次连接结果仍可查看。",
      "process": "进程",
      "protocol": "协议",
      "refresh": "刷新活动连接",
      "refreshOnce": "仅刷新一次",
      "remoteAddress": "远端地址",
      "resume": "恢复监控",
      "skipped": "{{count}} 个连接条目因系统限制未能读取。",
      "state": "状态",
      "states": {
        "close_wait": "关闭等待",
        "closed": "已关闭",
        "closing": "关闭中",
        "delete_tcb": "删除 TCB",
        "established": "已建立",
        "fin_wait1": "FIN 等待 1",
        "fin_wait2": "FIN 等待 2",
        "last_ack": "最终确认",
        "listen": "监听",
        "syn_received": "SYN 已接收",
        "syn_sent": "SYN 已发送",
        "time_wait": "时间等待",
        "unconnected": "无连接",
        "unknown": "未知"
      },
      "summary": "连接摘要",
      "table": "活动连接列表",
      "tcpUdp": "TCP / UDP",
      "title": "活动连接",
      "truncated": "列表仅展示采集结果的前 500 项。",
      "unattributed": "未报告",
      "unavailable": "暂时无法读取活动连接。",
      "updatedAt": "更新于 {{time}}",
      "updating": "正在更新",
      "waiting": "等待首次采集"
    },
    "description": "速率按真实采样间隔换算；累计值从本次启动 CoreRobin 开始。",
    "establishingBaseline": "正在建立网络吞吐基线…",
    "history": {
      "application": "按应用",
      "applications": "相关应用",
      "clear": "清空历史",
      "days": "{{count}} 天",
      "description": "按应用或域名查看更长时间的连接活动。",
      "details": "连接详情",
      "domain": "按域名",
      "domains": "域名与地址",
      "empty": "等待下一次活动连接采集。",
      "enable": "启用连接历史",
      "eyebrow": "本机可选记录",
      "firstSeen": "首次出现",
      "groupBy": "聚合方式",
      "lastSeen": "最后出现",
      "lookupFallback": "部分域名无法解析，已使用 IP 地址继续记录。",
      "observations": "{{count}} 次观察",
      "optIn": "连接历史可能包含应用名称、域名和远端 IP，因此默认关闭。启用后只保存在本机。",
      "portsAndProtocols": "端口与协议",
      "privacy": "只保存五分钟聚合记录；最多 5000 条，可随时关闭或清空。",
      "retention": "保留",
      "title": "连接历史与聚合"
    },
    "interfaceActivity": "接口活动",
    "interfaceStates": {
      "dormant": "待机",
      "down": "未连接",
      "lowerlayerdown": "网络接口未连接",
      "notpresent": "不存在",
      "other": "其他",
      "testing": "测试中",
      "unknown": "未知",
      "up": "已连接"
    },
    "interfaces": "网络接口",
    "local": "本机网络",
    "noInterfaces": "当前没有可展示的网络接口。",
    "noIp": "未报告 IP 地址",
    "noMac": "无 MAC 地址",
    "packets": "{{count}} 个数据包",
    "quality": {
      "anomalies": "异常次数",
      "anomalyCount": "{{count}} 次",
      "chartLabel": "最近 15 分钟网络质量趋势，共 {{count}} 个样本",
      "checking": "正在检查…",
      "description": "打开页面后每 30 秒检查；可选择在后台保留最长 7 天的五分钟聚合趋势。",
      "diagnostics": {
        "stages": {
          "dns": "域名解析",
          "independent_service": "备用服务",
          "internet": "互联网",
          "ipv4": "IPv4 网络",
          "ipv6": "IPv6 网络",
          "local_link": "本地网络"
        },
        "status": {
          "degraded": "受限",
          "failed": "失败",
          "passed": "可用",
          "unavailable": "未配置"
        },
        "title": "分层网络诊断"
      },
      "dns": "域名解析",
      "empty": "正在进行首次网络质量检查…",
      "eyebrow": "自动网络采样",
      "history": {
        "axisHours": "−{{count}} 小时",
        "axisMinutes": "−{{count}} 分钟",
        "clear": "清空质量历史",
        "description": "关闭页面后每五分钟轻量采样一次，只在本机保存聚合数值。",
        "hours1": "1 小时",
        "hours24": "24 小时",
        "minutes15": "15 分钟",
        "range": "趋势范围",
        "title": "持续质量记录",
        "window": "最近 {{count}} 小时 · 五分钟聚合"
      },
      "jitter": "抖动",
      "latency": "平均延迟",
      "legend": "网络质量图例",
      "loss": "连接失败",
      "method": "CoreRobin 会分别检查本地网络、域名解析和互联网连接，帮助判断问题发生在哪里。",
      "now": "现在",
      "probeAndTargets": "{{successful}}/{{total}} 次检查成功 · {{targetSuccessful}}/{{targetTotal}} 个服务可达",
      "probeSuccess": "{{successful}}/{{total}} 次成功",
      "probes": "连接检查",
      "run": "立即复测",
      "status": {
        "limited": "连接受限",
        "offline": "无法联网",
        "online": "联网正常"
      },
      "title": "网络质量",
      "trendCollecting": "正在积累趋势数据",
      "trendTitle": "网络质量趋势",
      "trendWindow": "最近 15 分钟 · 每 30 秒自动更新",
      "windowAverage": "平均延迟",
      "windowPeak": "峰值延迟"
    },
    "qualityEvents": {
      "eyebrow": "事件解释",
      "kind": {
        "direct_failure": "互联网直连路径出现异常",
        "dns_failure": "DNS 解析出现异常",
        "interface_change": "活动网络接口或默认路由发生切换",
        "sleep_gap": "电脑睡眠期间暂停采样",
        "status_change": "联网状态发生变化"
      },
      "none": "这个时间范围内没有值得注意的网络事件。",
      "privacy": "只保存事件类型、时间、状态和聚合值；不会保留接口名称或网络地址。",
      "summary": "最近 {{hours}} 小时：{{outage}} 次短暂中断、{{gap}} 个睡眠缺口、{{dns}} 次 DNS 异常、{{direct}} 次直连异常、{{interface}} 次接口切换。",
      "title": "网络发生过什么变化"
    },
    "qualityHistoryHours168": "7 天",
    "receive": "接收",
    "receiveNow": "当前接收",
    "receivePeak": "接收峰值",
    "send": "发送",
    "sendNow": "当前发送",
    "sendPeak": "发送峰值",
    "sessionContext": "接收 {{receive}} · 发送 {{send}}",
    "sessionTotal": "本次启动累计",
    "showOtherInterfaces": "显示另外 {{count}} 个接口",
    "sortedByTraffic": "按当前总流量排序",
    "summary": "网络摘要",
    "throughput": "网络吞吐",
    "throughputLegend": "吞吐图例",
    "title": "实时接口与会话流量",
    "unknownMtu": "未知"
  },
  "notifications": {
    "recovered": {
      "cpu": {
        "body": "处理器已稳定回到正常范围，之前的卡顿、发热或耗电影响应该正在缓解。",
        "title": "电脑负荷已经恢复"
      },
      "memory": {
        "body": "可用内存和交换活动已经稳定恢复，切换应用应该会更顺畅。",
        "title": "内存压力已经缓解"
      },
      "volume": {
        "body": "磁盘占用已稳定回到安全范围，目前不需要继续清理。",
        "title": "磁盘空间状态已经恢复"
      }
    },
    "test": {
      "body": "这是一条本机测试提醒。后续提醒仍会保持克制，可随时在设置中调整。",
      "title": "CoreRobin 提醒已就绪"
    },
    "triggered": {
      "cpu": {
        "body": "处理器持续繁忙，可能导致卡顿、发热或更耗电。打开 CoreRobin 可查看影响最大的应用。",
        "title": "电脑持续处于高负荷"
      },
      "memory": {
        "body": "低可用内存与明显交换活动同时出现，切换应用可能变慢。CoreRobin 不会自动关闭应用。",
        "title": "可用内存持续紧张"
      },
      "volume": {
        "body": "磁盘占用持续超过 85%。可以先打开清理页查看空间地图，文件处理仍需你确认。",
        "title": "磁盘剩余空间偏少"
      }
    },
    "watch": {
      "metric": {
        "cpu": "CPU {{value}}%",
        "disk": "磁盘活动 {{value}} MiB/s",
        "memory": "内存 {{value}} MiB"
      },
      "recovered": {
        "body": "{{metric}} 已回到设定阈值以下。",
        "title": "{{application}} 已恢复"
      },
      "triggered": {
        "body": "{{metric}} 已持续超过规则 {{seconds}} 秒。",
        "title": "{{application}} 达到关注条件"
      }
    }
  },
  "process": {
    "allProcesses": "所有进程",
    "background": {
      "collapse": "收起",
      "detail": {
        "previousParent": "此前所属进程",
        "source": "后台来源"
      },
      "filter": "仅看可能残留",
      "filterTitle": "只显示原应用退出后仍被连续多次观察到的进程",
      "inspect": "检查并处理",
      "kicker": "后台残留诊断",
      "observed": "已持续 {{duration}}",
      "safety": "系统服务、XPC 服务与应用扩展已排除；处理操作需要逐项核对。",
      "state": {
        "confirmed_owned_leftover": "已确认的 CoreRobin 残留任务",
        "likely_leftover": "可能残留",
        "managed": "由系统或应用管理",
        "unconfirmed": "来源尚未确认",
        "zombie": "已退出，等待系统回收"
      },
      "summary": "{{count}} 个进程在原应用退出后仍持续运行，占用 {{size}}",
      "title": "检测到可能残留的后台进程",
      "view": "查看"
    },
    "clearSearch": "清除进程筛选",
    "collapse": "折叠{{name}}",
    "columns": {
      "disk": "磁盘 I/O",
      "memory": "内存",
      "process": "进程",
      "status": "状态"
    },
    "dialog": {
      "bestEffortIdentity": "CoreRobin 会在执行前再次确认进程身份；如果目标已经变化，不会继续操作。",
      "confirmForce": "确认强制结束",
      "confirmRequest": "确认请求结束",
      "forceTitle": "强制结束进程？",
      "request": "先请求进程自行退出，让它有机会保存内容并完成清理。",
      "requestTitle": "请求进程结束？",
      "stableIdentity": "执行只会作用于你刚刚确认的这个进程；目标变化时会自动取消。",
      "startedAt": "启动时间",
      "unixForce": "将立即结束这个进程；它可能来不及保存当前内容，此操作不可撤销。",
      "user": "用户",
      "validating": "正在重新确认…",
      "windowsForce": "将立即结束这个进程；它可能来不及保存当前内容。"
    },
    "errors": {
      "busy": "同时打开的进程确认过多，请关闭一个后重试。",
      "noCloseWindow": "这个后台进程没有可供 Windows 请求关闭的应用窗口。只有明确了解风险时才使用强制结束。",
      "permissionDenied": "操作系统不允许 CoreRobin 控制这个进程。CoreRobin 不会自动请求管理员权限。",
      "targetChanged": "这个进程已经退出或发生变化，没有结束其他进程。",
      "unavailable": "当前系统无法对所选进程执行这项操作。"
    },
    "expand": "展开{{name}}",
    "flat": "平铺",
    "flatTitle": "平铺视图",
    "follow": "跟随",
    "followTitle": "刷新时保持选中进程在视野内",
    "footer": {
      "compact": "显示 {{visible}} / {{total}} 个进程",
      "flat": "{{visible}} / {{total}} 个进程 · 按需渲染",
      "liveOrder": "指标实时更新 · 顺序会随当前排序自动变化",
      "selectionFiltered": "选中进程被筛选隐藏 · 清除筛选",
      "siblingSort": "根层自动展开 · 同级排序",
      "stableOrder": "指标实时更新 · 顺序仅在手动排序时变化",
      "tree": "可见 {{visible}} · 匹配 {{matches}} / {{total}} 个进程"
    },
    "history": {
      "chartDescription": "当前 {{current}}，平均 {{average}}，峰值 {{peak}}。",
      "chartTitle": "{{name}} 的 {{metric}} 五分钟趋势",
      "diskIo": "磁盘 I/O",
      "empty": "选择进程后开始记录趋势。",
      "exited": "进程已退出，趋势停止更新。",
      "memory": "内存",
      "metrics": "趋势指标",
      "retained": "最多保留 5 分钟",
      "title": "资源趋势"
    },
    "inspector": {
      "allowBestEffort": "允许在执行前再次确认进程",
      "bestEffort": "CoreRobin 会在执行前再次确认进程仍是你选择的那个；如果目标已经变化，操作会被取消。",
      "binding": "正在确认目标…",
      "choose": "选择一个进程",
      "chooseDetail": "查看资源证据、父进程和安全操作。",
      "executable": "可执行文件",
      "exited": "进程已经退出",
      "exitedDetail": "旧选择不会自动绑定到复用该 PID 的新进程。",
      "forceKill": "强制结束…",
      "launchCommand": "启动命令",
      "multiCore": "该进程当前使用超过一个逻辑核心；进程 CPU 按单核 100% 计量。",
      "parent": "父进程",
      "requestClose": "请求结束",
      "residentMemory": "常驻内存",
      "restart": "重新启动应用",
      "runtime": "已运行",
      "stableHandle": "CoreRobin 会锁定你选择的进程，并在执行前再次确认它没有变化。",
      "unavailableControl": "此平台暂不支持安全的进程控制。",
      "userStatus": "用户 / 状态",
      "verifying": "正在核验进程身份…"
    },
    "liveSort": "实时排序",
    "liveSortTitle": "开启后，列表会随实时指标变化自动重新排序",
    "matchedPort": "匹配端口 {{port}}",
    "noMatches": "没有匹配的进程",
    "protected": "受保护",
    "realtime": "实时采样",
    "resetView": "恢复默认进程视图",
    "resort": "按当前指标重新排序",
    "search": "搜索进程",
    "searchPlaceholder": "名称、PID、用户或端口",
    "status": {
      "Dead": "退出",
      "Idle": "空闲",
      "LockBlocked": "锁等待",
      "Run": "运行",
      "Sleep": "休眠",
      "Stop": "停止",
      "UninterruptibleDiskSleep": "I/O 等待",
      "Zombie": "僵尸"
    },
    "systemProcesses": "系统进程",
    "topProcesses": "影响最大的进程",
    "tree": "树形",
    "treeTitle": "按父子关系显示；根层自动展开并按列排序同级进程",
    "viewMode": "视图模式",
    "viewSettings": "进程视图设置"
  },
  "settings": {
    "about": {
      "applyingUpdate": "正在安装更新",
      "architecture": "架构",
      "checkUpdate": "检查更新",
      "checking": "正在检查…",
      "clearAction": "清空全部数据",
      "clearConfirm": "此操作无法撤销。CoreRobin 将清除本机数据并重新启动；登录启动等系统授权不会被静默移除。",
      "clearDescription": "清除偏好、历史、提醒、操作记录和空间扫描索引。",
      "clearError": "部分本机数据未能清除，CoreRobin 不会把它显示成已完成。请关闭正在运行的扫描后重试。",
      "clearNow": "清空并重新启动",
      "clearScope": {
        "history": "资源历史、提醒历史和已确认的操作记录",
        "preferences": "界面偏好和各项功能的本机设置",
        "scans": "应用清单、空间地图缓存和文件分析结果"
      },
      "clearTitle": "清空全部本地数据",
      "clearing": "正在清空本机数据…",
      "description": "查看版本、获取帮助，并管理 CoreRobin 保存在这台电脑上的数据。",
      "diagnostics": {
        "copied": "已复制",
        "error": "复制失败",
        "idle": "复制脱敏诊断摘要"
      },
      "diagnosticsDescription": "复制有助于排查问题的基础运行信息。",
      "diagnosticsPreview": "复制前预览",
      "diagnosticsPrivacy": "默认不包含主机名、进程名、文件路径、网络地址或历史数值。",
      "diagnosticsTitle": "诊断摘要",
      "downloadingUpdate": "正在下载并验证更新",
      "guide": "用户指南",
      "helpDescription": "打开公开指南，或在提交前查看会包含哪些信息。",
      "helpTitle": "帮助与反馈",
      "installUpdate": "下载并安装",
      "installingUpdate": "正在更新…",
      "lastCheckFailed": "{{time}} 的后台检查失败，可点击“检查更新”重试。",
      "lastChecked": "上次检查：{{time}}",
      "openRelease": "前往下载",
      "platform": "系统",
      "privacy": "隐私说明",
      "releaseNotes": "查看更新内容",
      "remindLater": "明天提醒我",
      "reopenGuide": "重新查看首次引导",
      "reportIssue": "报告问题",
      "restartUpdate": "立即重启并完成更新",
      "restartingUpdate": "正在重新启动…",
      "skipVersion": "跳过 v{{version}}",
      "title": "关于与支持",
      "upToDate": "已是最新版本 v{{version}}",
      "updateAvailable": "CoreRobin v{{version}} 已发布",
      "updateError": "暂时无法检查更新，请稍后重试。",
      "updateInstallError": "更新未能安装。当前版本没有变化，请稍后重试或查看更新内容。",
      "updateReady": "更新已安装并准备就绪。重新启动后将直接使用新版本。",
      "updateRestartError": "更新已经安装，但 CoreRobin 未能自动重新启动。请重试，或手动退出后重新打开。",
      "updatedCompact": "已更新",
      "updatedReceipt": "已从 v{{version}} 成功更新",
      "version": "当前版本",
      "versionDescription": "直接在 CoreRobin 中检查、下载并安装最新稳定版本。",
      "versionTitle": "版本与更新",
      "whatsNew": "这个版本的新内容"
    },
    "applicationImpactHistory": {
      "hint": "需要先开启本机历史并允许保存应用显示名；不会保存命令或文件路径。",
      "label": "保留应用影响聚合"
    },
    "background": {
      "companionAlwaysOnTop": "Robin 始终置顶",
      "companionAlwaysOnTopDescription": "保持在其他窗口上方，关闭后可能被遮挡",
      "companionShowOnStartup": "让 Robin 常驻桌面",
      "companionShowOnStartupDescription": "应用启动后自动显示 Robin",
      "description": "控制 CoreRobin 如何常驻、登录启动，以及 Robin 的桌面行为。",
      "launchAtLogin": "登录时启动",
      "launchAtLoginDescription": "登录后静默启动状态栏服务，不自动打开主窗口",
      "showDockIcon": "在 Dock 中显示",
      "showDockIconDescription": "关闭后不占用 Dock 和应用切换器，仍可从顶部状态栏唤起",
      "title": "后台与桌面"
    },
    "connections": {
      "description": "活动连接使用独立的低频扫描，不影响系统主采样。",
      "refresh": "活动连接",
      "title": "连接刷新"
    },
    "dataPrivacy": {
      "caches": {
        "description": "应用清单、空间扫描和文件分析结果只保存在这台设备上。",
        "title": "本机产品缓存"
      },
      "categories": {
        "applicationInventory": {
          "description": "按界面语言保存的已安装应用元数据，不包含应用内容。",
          "title": "应用清单缓存"
        },
        "connectionHistory": {
          "description": "可选的五分钟聚合记录，可能包含远端地址、端口和应用名。",
          "title": "连接历史"
        },
        "resourceHistory": {
          "description": "整机资源、提醒、应用关注和本机操作记录。",
          "title": "资源与操作历史"
        },
        "scanCaches": {
          "description": "原生空间扫描索引与文件洞察结果包含路径、大小和修改时间。",
          "title": "扫描索引与结果"
        }
      },
      "clear": "清空全部本机数据",
      "clearAll": {
        "description": "统一确认后清除以上数据、偏好设置和本机界面状态。",
        "title": "清除全部产品数据"
      },
      "connectionHistory": {
        "description": "可选的五分钟聚合数据可能包含远端 IP、域名、端口和应用名。",
        "title": "连接历史"
      },
      "description": "集中查看每类本机数据包含什么并进行控制。CoreRobin 不会上传或同步这些记录。",
      "diskAccess": {
        "description": "这项可选权限由 macOS 管理；返回 CoreRobin 后会自动刷新状态。",
        "open": "打开系统设置",
        "title": "完全磁盘访问权限"
      },
      "metrics": {
        "cleanupIndex": "空间扫描索引占用：{{size}}",
        "items": "{{count}} 项",
        "never": "尚无本机数据",
        "retention": "保留 {{count}} 天",
        "session": "仅当前会话",
        "updated": "更新于 {{time}}"
      },
      "resourceHistory": {
        "description": "整机健康、操作和关注事件的聚合记录，不含路径、命令或网络地址。",
        "title": "资源与提醒历史"
      },
      "result": {
        "clear": "清除此类",
        "failed": "清除失败",
        "retry": "重试",
        "skipped": "因其他项目失败而跳过",
        "succeeded": "已清除"
      },
      "status": {
        "off": "已关闭",
        "on": "正在保存"
      },
      "title": "数据与隐私中心"
    },
    "description": "这些偏好只保存在当前设备上，并会立即应用到采样与界面。",
    "experience": {
      "description": "日常模式从实际问题出发并给出引导；专业模式保留完整进程与指标。",
      "label": "界面模式",
      "professional": "专业模式",
      "sectionDescription": "选择界面模式和显示语言。",
      "sectionTitle": "界面与语言",
      "simple": "日常模式",
      "title": "界面模式"
    },
    "history": {
      "applicationNames": "允许历史保存应用显示名",
      "applicationNamesHint": "仅当某个应用明显解释资源压力时保存名称；关闭后会移除已保存事件中的应用名。",
      "days": "{{count}} 天",
      "description": "保存整机资源的低频聚合快照与告警事件，不包含进程与连接详情。",
      "persist": "在本机保存历史",
      "retention": "保留时间",
      "title": "历史记录"
    },
    "intervalMs": "{{interval}} 毫秒",
    "intervalSeconds": "{{seconds}} 秒",
    "language": {
      "description": "切换 CoreRobin 的菜单、说明与状态文本。",
      "label": "语言",
      "title": "界面语言"
    },
    "localPreferences": "本机偏好",
    "notifications": {
      "categories": "允许提醒的类别",
      "delivery": {
        "failed": "上次提醒在 {{time}} 发送失败，请测试或检查系统设置",
        "sent": "上次提醒已于 {{time}} 交给系统"
      },
      "description": "只提醒持续高负荷、真实内存压力和磁盘空间不足；问题稳定恢复后会再告知一次。",
      "enable": "允许克制提醒",
      "openSettings": "打开系统通知设置",
      "resources": {
        "cpu": "持续高负荷",
        "memory": "内存压力",
        "volume": "磁盘空间"
      },
      "status": {
        "denied": "系统未授权",
        "disabled": "未开启",
        "ready": "已允许",
        "requesting": "等待系统授权",
        "unavailable": "仅桌面应用可用"
      },
      "test": "发送测试提醒",
      "title": "桌面提醒"
    },
    "onboarding": {
      "back": "上一步",
      "controls": {
        "diskAccess": "完整磁盘访问",
        "diskAccessStatus": {
          "granted": "已就绪",
          "not_granted": "可选 · 尚未授权",
          "not_required": "此系统无需授权",
          "unknown": "暂时无法确认状态"
        },
        "everyday": "清晰结论和引导操作",
        "mode": "选择体验模式",
        "openDiskAccess": "打开完整磁盘访问设置",
        "professional": "完整指标和诊断证据"
      },
      "finish": "开始使用",
      "kicker": "首次使用 · {{current}} / {{total}}",
      "next": "下一步",
      "skip": "暂时跳过",
      "steps": {
        "one": {
          "description": "日常模式会给出稳定结论和下一步；专业模式保留完整指标、进程和网络证据。你可以随时切换。",
          "note": "两种模式使用同一份本机状态，不会产生不同结论。",
          "title": "先选择适合你的查看方式"
        },
        "three": {
          "description": "通知、Robin 和登录启动均可选。只有进行空间清理时，完整磁盘访问才可能让扫描更完整。",
          "note": "不授权仍可扫描系统允许访问的区域；CoreRobin 不会在这里主动请求权限。",
          "title": "权限按需要使用，由你决定"
        },
        "two": {
          "description": "CoreRobin 会留在状态栏继续低频采样。状态栏面板和 Robin 共享同一份稳定状态。",
          "note": "可以从状态栏暂停、打开设置或彻底退出应用。",
          "title": "关闭窗口后仍会安静守候"
        }
      }
    },
    "processView": {
      "description": "启动与重置进程浏览器时使用的布局。",
      "label": "默认进程视图",
      "title": "默认进程视图"
    },
    "sampling": {
      "advanced": "高级：精确采样间隔",
      "description": "更短的间隔响应更快，也会带来更高的采样开销。",
      "presets": {
        "balanced": {
          "description": "1 秒一次，推荐日常使用",
          "label": "平衡"
        },
        "lowPower": {
          "description": "5 秒一次，适合长期后台运行",
          "label": "低功耗"
        },
        "realtime": {
          "description": "0.5 秒一次，响应更快",
          "label": "实时"
        }
      },
      "system": "CPU、内存与进程",
      "title": "系统采样"
    },
    "supportFlow": {
      "action": "准备问题反馈",
      "confirm": "复制并打开 Issue",
      "copyDescription": "把同一份脱敏摘要复制到剪贴板，方便补充或复用。",
      "copyTitle": "复制",
      "description": "先核对即将复制的内容，再打开已经预填的公开 GitHub Issue。",
      "diagnosticHeading": "隐私脱敏环境摘要",
      "error": "无法复制摘要或打开 Issue 表单，请重试。",
      "issueTitle": "[v{{version}}] 问题反馈",
      "openDescription": "预填版本、系统、架构和复现步骤提示，由你填写问题描述。",
      "openTitle": "打开 Issue",
      "opening": "正在准备反馈…",
      "preview": "即将复制并写入 Issue 的内容",
      "problemHeading": "发生了什么",
      "problemPlaceholder": "<!-- 请描述问题和预期结果。 -->",
      "reviewDescription": "确认摘要中没有你不希望分享的信息。",
      "reviewTitle": "预览",
      "stepsHeading": "复现步骤",
      "stepsPlaceholder": "<!-- 请列出最短的复现步骤。 -->",
      "title": "准备一份脱敏的问题反馈"
    },
    "thresholds": {
      "critical": "严重",
      "description": "用于 CPU、内存与卷占用的颜色分级；持续达到“偏高”时记录告警。",
      "high": "偏高",
      "low": "正常",
      "moderate": "关注",
      "preview": "资源告警颜色预览",
      "title": "资源告警阈值"
    },
    "title": "设置",
    "transfer": {
      "apply": "应用导入设置",
      "boundary": "只包含偏好和关注规则；不导出历史、文件路径、连接记录或扫描结果。",
      "description": "通过明确选择的本机 JSON 文件，在电脑之间迁移 CoreRobin 偏好和应用关注规则。",
      "export": "导出设置",
      "import": "导入设置",
      "invalid": "这不是受支持的 CoreRobin 偏好备份文件。",
      "noChanges": "没有设置会发生变化",
      "preview": "{{count}} 项设置不同 · {{rules}} 条应用关注规则",
      "previewTitle": "复核将要导入的变化",
      "title": "偏好与规则备份"
    },
    "watchRules": {
      "active": "条件已达到",
      "add": "添加规则",
      "application": "应用",
      "applicationPlaceholder": "选择或输入应用名称",
      "backgroundSampling": "启用规则期间，后台每 {{seconds}} 秒检查一次应用进程。",
      "description": "关注指定应用；指标持续达到条件时发送一次通知，并在恢复后允许再次提醒。",
      "duration": "持续时间",
      "empty": "尚未添加应用关注规则。",
      "metric": "指标",
      "metrics": {
        "cpu": "CPU",
        "disk": "磁盘活动",
        "memory": "内存"
      },
      "notificationHint": "打开桌面通知并授予权限后，规则才能发送系统提醒。",
      "remove": "移除 {{name}} 的提醒规则",
      "seconds": "{{count}} 秒",
      "summary": "{{metric}} ≥ {{threshold}}{{unit}}，持续 {{seconds}} 秒",
      "threshold": "阈值",
      "title": "应用关注与提醒规则"
    }
  },
  "splash": {
    "connecting": "正在连接本机采样器",
    "description": "本机资源状态，清晰呈现。",
    "title": "正在启动 CoreRobin"
  },
  "startup": {
    "actionDialog": {
      "applying": "正在安全更新…",
      "disable": {
        "confirm": "确认停用自动启动",
        "description": "CoreRobin 会把这份用户级启动配置移到自己的可恢复存储中，不会删除它。",
        "title": "停用 {{name}} 的自动启动？",
        "whenDescription": "下次登录时生效；恢复后也会从下一次登录开始重新允许自动启动。"
      },
      "effect": "生效时间",
      "enable": {
        "confirm": "确认恢复自动启动",
        "description": "CoreRobin 会把之前保存的配置放回原位置。",
        "title": "恢复 {{name}} 的自动启动？",
        "whenDescription": "从下次登录开始，系统会再次允许这个项目自动启动。"
      },
      "errors": {
        "startup_confirmation_expired": "启动项状态刚刚发生变化，CoreRobin 没有执行操作。",
        "startup_confirmation_unavailable": "启动项状态刚刚发生变化，CoreRobin 没有执行操作。",
        "startup_destination_conflict": "目标位置出现了另一份配置，为避免覆盖，CoreRobin 没有执行操作。",
        "startup_item_protected": "这不是可安全管理的用户级第三方启动项，CoreRobin 没有执行操作。",
        "startup_item_unavailable": "这个启动项已经变化或不存在，请刷新列表后再试。",
        "startup_management_failed": "系统未能安全移动启动配置；原文件仍保留在当前状态。",
        "startup_state_changed": "启动配置在确认后发生变化，CoreRobin 没有执行操作。"
      },
      "owner": "所属应用",
      "preparing": "正在核对启动项与文件状态…",
      "reversibleDescription": "配置文件只会在两个用户目录之间移动，不会被编辑或删除。",
      "reversibleTitle": "随时可以恢复",
      "runningDescription": "停用自动启动不会关闭正在运行的应用，也不会中断正在进行的工作。",
      "runningTitle": "当前应用会继续运行",
      "source": "启动来源",
      "whenTitle": "不会立刻改变当前会话"
    },
    "actions": {
      "disable": "停用开机启动",
      "enable": "恢复开机启动",
      "openSettings": "前往系统设置管理"
    },
    "advice": {
      "disabled": {
        "description": "配置仍然存在，但系统不会按该条目自动启动。",
        "title": "当前未启用"
      },
      "normal": {
        "description": "通常只在更新、同步或特定事件发生时启动，不一定拖慢登录。",
        "title": "按条件运行"
      },
      "review": {
        "description": "每次登录都会启动；如果你不常用它，可以确认后停用。",
        "title": "可评估是否需要"
      },
      "system": {
        "description": "不建议作为普通启动项处理，CoreRobin 保持只读展示。",
        "title": "系统或设备服务"
      }
    },
    "backgroundCount": "后台活动",
    "backgroundHint": "按条件运行的同步、更新与维护助手",
    "completeScan": "已读取全部可用启动来源",
    "currentUse": {
      "high": "当前资源占用较高",
      "low": "当前资源占用较低",
      "moderate": "当前资源占用中等",
      "none": "当前未运行",
      "notMatched": "当前没有匹配到正在运行的应用",
      "running": "当前占用：CPU {{cpu}} · 内存 {{memory}}"
    },
    "description": "查看会在登录时或后台条件满足时启动的项目，优先解释第三方项目，不把系统服务包装成普通开关。",
    "disabled": "已停用",
    "disabledCount": "已停用",
    "disabledHint": "CoreRobin 可随时恢复的项目",
    "emptyDescription": "可以切换到“全部”查看按条件启动和系统维护项目。",
    "emptyTitle": "没有需要查看的项目",
    "enabled": "会自动启动",
    "eyebrow": "开机与登录",
    "filter": {
      "all": "全部",
      "background": "后台活动",
      "disabled": "已停用",
      "login": "登录时打开",
      "review": "建议查看",
      "system": "系统项目"
    },
    "filters": "启动项筛选",
    "guided": {
      "clear": "没有需要处理的第三方登录项",
      "clearDescription": "系统服务和按条件运行的维护项目不会被当成普通开关。",
      "description": "这里只列出登录时启动且可以安全恢复的第三方项目。",
      "found": "找到 {{count}} 个值得评估的项目",
      "foundDescription": "不常用的应用可以确认后停用，下次登录时生效。",
      "kicker": "第三方登录项",
      "title": "值得评估的开机项目"
    },
    "impact": {
      "boundary": "这是登录后影响测量，不是固件开机耗时；最多测量 3 分钟，并保留最近 5 次。",
      "description": "仅在 CoreRobin 被系统作为登录项静默启动时采样，记录到系统趋于稳定为止。",
      "empty": "还没有真实登录启动记录。启用后，CoreRobin 会在下一次登录时自动测量。",
      "enableLogin": "启用登录时启动",
      "eyebrow": "登录启动实测",
      "high": {
        "title": "当前后台影响较高"
      },
      "loginEnabled": "登录时启动已启用；下一次登录后会自动生成记录。",
      "low": {
        "title": "预计影响较低"
      },
      "moderate": {
        "title": "可能影响登录速度"
      },
      "none": {
        "title": "当前无启动影响"
      },
      "notMatched": "未匹配到当前正在运行的应用",
      "peakCpu": "CPU 峰值",
      "peakDisk": "磁盘峰值",
      "running": "当前运行：CPU {{cpu}} · 内存 {{memory}}",
      "samples": "采样数",
      "settleTime": "趋稳时间",
      "title": "真实登录启动影响"
    },
    "impactComparison": {
      "description": "使用前 {{count}} 次测量的中位数作为参照。",
      "improved": "趋稳速度快了 {{value}}%",
      "risingApplication": "{{name}} 上升最多，增加 {{value}} 个 CPU 百分点",
      "similar": "接近最近的中位数",
      "slower": "趋稳速度慢了 {{value}}%",
      "title": "与最近几次启动对比"
    },
    "impactReceipt": {
      "multiple": {
        "improved": "进行了 {{count}} 项启动项变更后，观察到下次启动趋稳更快；无法归因给其中某一项。",
        "similar": "进行了 {{count}} 项启动项变更后，下次启动与近期状态接近。",
        "slower": "进行了 {{count}} 项启动项变更后，下次启动仍然偏慢；无法判断由其中哪一项造成。"
      },
      "single": {
        "improved": "调整 {{name}} 后，观察到下次启动趋稳更快；单次观察不能证明改善由这个条目造成。",
        "similar": "调整 {{name}} 后，下次启动与近期状态接近。",
        "slower": "调整 {{name}} 后，下次启动仍然偏慢；它可能不是主要原因。"
      },
      "title": "启动项变更后的观察"
    },
    "inventory": "启动项清单",
    "listTitle": "哪些内容会自动启动",
    "loadingDescription": "CoreRobin 只读取系统公开的启动配置，不会加载或运行其中的命令。",
    "loadingTitle": "正在读取启动位置",
    "loginCount": "登录时打开",
    "loginHint": "登录后自动启动的应用与助手",
    "managementBoundary": "只有可恢复的用户级第三方启动文件可以停用；系统项目和不支持的来源保持只读。",
    "managementStatus": {
      "protected": "受保护项目",
      "system": "系统项目只读",
      "unsupported": "此来源暂不支持管理"
    },
    "openSettingsFailed": "未能打开系统设置，请重试，或在系统设置中手动打开“登录项”。",
    "outcome": {
      "disabled": "已停用 {{name}} 的自动启动；当前应用不会被关闭。",
      "enabled": "已恢复 {{name}} 的自动启动。",
      "undo": "撤销"
    },
    "ownership": {
      "itemCount": "{{count}} 个项目",
      "lastRun": "系统最近报告状态：{{status}}",
      "modern": "现代后台项目",
      "moreItems": "另外 {{count}} 个辅助项目",
      "orphaned": "可执行文件已不存在",
      "signature": {
        "invalid": "签名无效",
        "system_reported": "由 macOS 报告",
        "unknown": "签名状态未知",
        "valid": "签名有效"
      }
    },
    "partialScan": "结果不完整：发现 {{count}} 个启动来源问题",
    "publisherUnknown": "发布者未知",
    "readOnlyBoundary": "当前平台没有可安全恢复的启动项来源，因此只读展示。",
    "reviewCount": "建议看一眼",
    "reviewHint": "登录时启动的第三方项目",
    "scanFailed": "暂时无法读取启动项。没有修改任何内容，请重试。",
    "scanIssue": {
      "invalid_entry": "已跳过 {{count}} 个无效条目",
      "source_unavailable": "该来源暂时没有响应",
      "unreadable_location": "{{count}} 个位置无法读取"
    },
    "scanning": "正在检查…",
    "search": "搜索名称、发布者或路径",
    "showMore": "再显示 {{count}} 项",
    "showingCount": "正在展示 {{shown}} / {{total}} 项",
    "source": {
      "background_task": "登录项与后台项目",
      "desktop_entry": "自动启动条目",
      "launch_agent": "LaunchAgent",
      "launch_daemon": "LaunchDaemon",
      "registry_run": "注册表 Run",
      "startup_folder": "启动文件夹"
    },
    "summary": "启动项摘要",
    "systemCount": "系统项目",
    "systemHint": "保持只读，不提供普通开关",
    "technicalDetails": "查看文件与启动命令",
    "thirdPartyCount": "第三方项目",
    "thirdPartyHint": "包含按条件启动的后台助手",
    "title": "启动项",
    "unreadable": "{{count}} 个启动位置因权限不足未能读取"
  },
  "storage": {
    "available": "可用 {{value}}",
    "chartLabel": "磁盘读取 {{read}}，写入 {{write}}",
    "currentRead": "当前读取",
    "currentWrite": "当前写入",
    "description": "卷容量来自当前系统快照；吞吐按真实采样间隔换算。",
    "eject": {
      "action": "推出",
      "confirm": "确认推出",
      "ejecting": "正在推出…",
      "failed": "无法推出这个卷。请关闭正在使用它的文件后重试。",
      "noLongerRemovable": "这个卷已不再作为可移除卷提供。",
      "success": "已安全推出 {{name}}。"
    },
    "establishingBaseline": "正在建立磁盘吞吐基线…",
    "filesystemCapacity": "文件系统容量",
    "health": {
      "cached": "最近缓存结果",
      "description": "只展示操作系统提供的状态；CoreRobin 不修复磁盘，也不虚构健康百分比。",
      "external": "外置介质",
      "eyebrow": "只读设备信息",
      "filesystem": "文件系统",
      "hdd": "机械硬盘",
      "inspectUnavailable": "操作系统未能提供这个卷的全部详情。",
      "loading": "正在读取已挂载卷信息…",
      "media": "介质",
      "mountMode": "挂载模式",
      "openUtility": "打开磁盘工具",
      "purgeable": "可清理空间",
      "readOnly": "只读",
      "readWrite": "可读写",
      "retry": "重试这个卷",
      "scope": "S.M.A.R.T. 是操作系统可提供时的总体设备状态；不支持并不代表磁盘不健康。",
      "ssd": "固态硬盘",
      "status": {
        "failing": "可能故障",
        "unknown": "未知",
        "unsupported": "不支持",
        "verified": "已验证",
        "warning": "需要留意"
      },
      "title": "磁盘健康与挂载详情",
      "unknownMedia": "未知",
      "updatedNow": "刚刚检查"
    },
    "highestUsage": "最高占用",
    "inspectHint": "点击后在右侧核验详情",
    "local": "本机存储",
    "lowSpace": "空间偏紧",
    "noDisplayVolumes": "当前没有可展示的卷。",
    "noVolume": "无可用卷",
    "openCleanup": "分析空间",
    "readPeak": "读取峰值",
    "removable": "可移除",
    "snapshot": "当前快照",
    "sortedByUsage": "按占用率排序",
    "summary": "存储摘要",
    "throughput": "磁盘吞吐",
    "throughputLegend": "吞吐图例",
    "title": "容量与磁盘活动",
    "topProcesses": "磁盘活动最高的进程",
    "unnamedVolume": "未命名卷",
    "usedSpace": "{{name}} 已用空间",
    "volumeCount": "{{count}} 个卷",
    "volumes": "卷",
    "waitingProcessIo": "正在等待进程磁盘活动基线…",
    "writePeak": "写入峰值"
  },
  "tray": {
    "available": "可用空间",
    "cleanup": "空间清理",
    "companion": "Robin",
    "dataMode": {
      "background": "后台采样",
      "foreground": "前台采样"
    },
    "dataStatus": {
      "paused": "数据已暂停",
      "stale": "数据已过期"
    },
    "health": {
      "attention": "需要关注",
      "loading": "连接中",
      "normal": "状态正常",
      "observing": "正在了解状态",
      "urgent": "建议处理"
    },
    "incidentTitle": {
      "attention": "有 {{count}} 项情况值得留意",
      "urgent": "有 {{count}} 项情况建议尽快查看"
    },
    "localMonitor": "本机资源监控",
    "open": "打开概览",
    "quit": "退出应用",
    "reason": "{{resource}}需要关注",
    "recovering": "指标已回落，正在确认是否恢复。",
    "resource": {
      "battery": "电池",
      "cpu": "处理器",
      "memory": "内存",
      "network": "网络",
      "none": "系统",
      "sleep": "休眠",
      "storage": "存储",
      "temperature": "温度"
    },
    "status": {
      "attention": {
        "description": "打开 CoreRobin 可以查看原因和对应建议。",
        "title": "有一项资源值得留意"
      },
      "loading": {
        "description": "首个采样结果很快就会出现。",
        "title": "正在读取电脑状态"
      },
      "normal": {
        "description": "没有发现需要立即处理的资源问题。",
        "title": "电脑运行平稳"
      },
      "observing": {
        "description": "再观察一会儿，避免把短暂波动误判成问题。",
        "title": "正在了解电脑状态"
      },
      "stale": {
        "description": "主界面采样连接已中断；重新打开 CoreRobin 后会自动恢复。",
        "title": "暂时没有收到新的电脑状态"
      },
      "urgent": {
        "description": "建议打开 CoreRobin 查看证据后再处理。",
        "title": "有一项资源压力较高"
      }
    },
    "updateAvailable": "CoreRobin v{{version}} 可以安装",
    "updatedAt": "{{time}} 更新"
  },
  "wellbeing": {
    "battery": {
      "attention": "剩余电量不多，建议准备连接电源",
      "cycleCountLabel": "循环次数",
      "healthLabel": "健康度",
      "label": "电池",
      "normal": "电量状态正常",
      "notPresent": "未检测到电池",
      "remaining": "约 {{hours}} 小时 {{minutes}} 分钟",
      "state": {
        "charging": "正在充电",
        "discharging": "正在使用电池",
        "full": "已充满",
        "not_charging": "已接电源，未充电",
        "unknown": "状态未知"
      },
      "unavailable": "台式机或未提供电池信息的设备会显示在这里。",
      "urgent": "电量很低，建议尽快连接电源"
    },
    "description": "低频读取系统状态，并解释是否有应用让电脑无法自动休眠。",
    "eyebrow": "设备状态",
    "overall": {
      "attention": "需要留意",
      "normal": "状态正常",
      "unavailable": "系统未提供读数",
      "urgent": "建议处理"
    },
    "readiness": {
      "battery": {
        "unavailable": "检测到电池，但本次状态读取失败；应用会继续重试。",
        "unsupported": "未检测到电池；台式机等设备通常属于正常情况。",
        "waiting": "正在等待第一次电池采样。"
      },
      "batteryDetails": {
        "unavailable": "电量读取正常，但系统暂未提供健康度或循环次数。",
        "unsupported": "这台设备没有提供电池详情。",
        "waiting": "正在读取电池健康度和循环次数。"
      },
      "lastSuccessful": "上次成功读取：{{time}}",
      "short": {
        "available": "可用",
        "unavailable": "暂时不可用",
        "unsupported": "系统未提供",
        "waiting": "等待首个样本"
      },
      "temperature": {
        "unavailable": "之前可以读取温度，但这次读取失败；应用会继续低频重试。",
        "unsupported": "当前系统或硬件没有提供可识别的温度传感器。",
        "waiting": "正在等待第一次温度采样。"
      },
      "why": "为什么没有读数？"
    },
    "sleep": {
      "blocked": "{{name}} 正在阻止自动休眠，已持续{{duration}}{{more}}。退出应用或暂停相关任务后通常会恢复。",
      "blockedValue": "{{count}} 个应用",
      "blockedValue_one": "{{count}} 个应用",
      "blockedValue_other": "{{count}} 个应用",
      "clear": "没有发现应用阻止电脑自动休眠。",
      "clearValue": "可以正常休眠",
      "duration": {
        "hours": "约 {{count}} 小时",
        "hours_one": "约 1 小时",
        "hours_other": "约 {{count}} 小时",
        "lessThanMinute": "不到 1 分钟",
        "minutes": "约 {{count}} 分钟",
        "minutes_one": "约 1 分钟",
        "minutes_other": "约 {{count}} 分钟",
        "unknown": "一段时间"
      },
      "label": "自动休眠",
      "more": "，另有 {{count}} 个应用",
      "system": "系统任务暂时保持电脑唤醒，通常无需处理，也不建议结束系统进程。",
      "systemValue": "系统活动",
      "unavailable": "当前平台没有向 CoreRobin 提供可靠的休眠阻止信息。",
      "unavailableValue": "无法读取"
    },
    "temperature": {
      "attention": "设备有些热；如果同时卡顿，可先减少高负荷任务。",
      "label": "设备温度",
      "normal": "当前温度在正常范围内。",
      "unavailable": "当前系统或硬件没有向 CoreRobin 提供温度读数。",
      "urgent": "温度持续偏高，建议停止高负荷任务并保持通风。"
    },
    "title": "温度、电池与休眠"
  }
}
